{
  "compatibilityLevel": 1601,
  "model": {
    "annotations": [
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.138.1452.0 (24.11)"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"EdmSales vbSalesAndProfit\",\"Distribution Channel\",\"Business Group\",\"EdmMasterData dConversion\",\"Units Conversion\",\"Measures Table\",\"Currency\",\"Sort Matrix Table\",\"Profit name\",\"Source Table\",\"EdmMasterData dDivision\",\"EdmMasterData dMarketEndUse\",\"EdmPlant dPlant\",\"EdmMasterData dSalesOrganisation\",\"EdmMasterData dSalesType\",\"EdmMasterData dExportIndicator\",\"EdmMasterData dTransportMode\",\"EdmCompany dCompany\",\"EdmMasterData dProfitCenter\",\"EdmMasterData dBusinessUnit\",\"EdmMasterData dIncoterms\",\"EdmVendor dVendor\",\"EdmMasterData dPackageType\",\"EdmMaterial dMaterial\",\"EdmCustomer dSoldToCustomer\",\"EdmCustomer dShipToCustomer\",\"EdmMasterData dCountry\",\"Last Refreshed Date Time\",\"Final Destination County Zone\",\"server\",\"warehouse\",\"db\",\"role\"]"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {}
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "expressions": [
      {
        "name": "server",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ],
        "expression": "\"lyb-main.privatelink.snowflakecomputing.com\" meta [IsParameterQuery=true, Type=\"Text\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "a59bec6a-8027-4c87-96f5-82cc689c1c87",
        "queryGroup": "Parameters"
      },
      {
        "name": "warehouse",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ],
        "expression": "\"DEV_PBI_WH_01\" meta [IsParameterQuery=true, Type=\"Text\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "a25fd116-9e23-460f-a1b2-fcb1f9a1c92b",
        "queryGroup": "Parameters"
      },
      {
        "name": "db",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Text"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "expression": "\"DEV_SOURCE\" meta [IsParameterQuery=true, Type=\"Text\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "0ea83d42-5ff7-4501-b153-7bd9e5db2eea",
        "queryGroup": "Parameters"
      },
      {
        "name": "role",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Text"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "expression": "\"AZG_IAM_DAPLATFORM_SNOWFLAKE_MIGRATION_DATA_VISUALIZATION\" meta [IsParameterQuery=true, Type=\"Text\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "d958dd2a-294f-4475-b2dc-ff34c2d3ac22",
        "queryGroup": "Parameters"
      }
    ],
    "queryGroups": [
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "Parameters"
      }
    ],
    "relationships": [
      {
        "name": "63df635a-bd35-4884-ad78-9be999259949",
        "fromColumn": "Distribution Channel",
        "fromTable": "EdmSales vbSalesAndProfit",
        "toColumn": "Distribution Channel",
        "toTable": "Distribution Channel"
      },
      {
        "name": "155afbfc-a811-4806-9f3f-c508a42b1c19",
        "fromColumn": "Business Group",
        "fromTable": "EdmSales vbSalesAndProfit",
        "toColumn": "Business Group",
        "toTable": "Business Group"
      },
      {
        "name": "2d0653a7-2d62-4d7c-8460-729ef57db08c",
        "fromColumn": "Date",
        "fromTable": "Date Table",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_a3e90990-2659-4fbc-a79d-2683b663011e"
      },
      {
        "name": "27b711a4-033b-4701-9fc0-9d1652be9a77",
        "fromColumn": "COM Inv Date",
        "fromTable": "EdmSales vbSalesAndProfit",
        "toColumn": "Date",
        "toTable": "Date Table"
      },
      {
        "name": "04ff5f92-8636-4ef5-b9cf-3535722bdc7a",
        "fromColumn": "Todays Date",
        "fromTable": "Date Table",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_8e68eb8c-b300-45b5-9474-1d794476bef1"
      },
      {
        "name": "6c48537e-3308-4526-9fdd-8e8bee6446ca",
        "fromColumn": "Max Date",
        "fromTable": "Date Table",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_4b4b43bf-cb33-40ba-8d24-f0de07093abd"
      },
      {
        "name": "7d175f6a-e8ec-4126-93ce-75a6c5f8b593",
        "crossFilteringBehavior": "bothDirections",
        "fromCardinality": "one",
        "fromColumn": "Profitability Matrix Order",
        "fromTable": "Profitability Matrix",
        "toColumn": "Sort no",
        "toTable": "Profit name"
      },
      {
        "name": "008f156e-34e3-4ae6-b0e1-5f22e1d77ee7",
        "fromColumn": "Vendor",
        "fromTable": "EdmSales vbSalesAndProfit",
        "toColumn": "Vendor",
        "toTable": "EdmVendor dVendor"
      },
      {
        "name": "d00c24d1-857e-4b1d-9e5d-0d5e615def6e",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "Division",
        "fromTable": "EdmSales vbSalesAndProfit",
        "toColumn": "Division",
        "toTable": "EdmMasterData dDivision"
      },
      {
        "name": "73811c3f-7778-4eb0-8a0d-e40df15cc51d",
        "fromColumn": "Company Code",
        "fromTable": "EdmSales vbSalesAndProfit",
        "toColumn": "Company",
        "toTable": "EdmCompany dCompany"
      },
      {
        "name": "3db8a563-e7be-4f49-84db-b4e2accf3960",
        "fromColumn": "Incoterms",
        "fromTable": "EdmSales vbSalesAndProfit",
        "toColumn": "Incoterms",
        "toTable": "EdmMasterData dIncoterms"
      },
      {
        "name": "b6e9cb7a-9c49-46a5-9029-b4537b40fe1c",
        "fromColumn": "Export Indicator",
        "fromTable": "EdmSales vbSalesAndProfit",
        "toColumn": "Export Indicator",
        "toTable": "EdmMasterData dExportIndicator"
      },
      {
        "name": "7d013551-2321-4f63-8220-e463b38469a6",
        "fromColumn": "Plant",
        "fromTable": "EdmSales vbSalesAndProfit",
        "toColumn": "Plant",
        "toTable": "EdmPlant dPlant"
      },
      {
        "name": "3be4e961-f4a4-4db2-beaf-5dcda3e9a856",
        "fromColumn": "Package Type",
        "fromTable": "EdmSales vbSalesAndProfit",
        "toColumn": "Matl Pricing Grp 4",
        "toTable": "EdmMasterData dPackageType"
      },
      {
        "name": "b07ebfd9-069f-40a3-8224-455152679036",
        "fromColumn": "Profit Center",
        "fromTable": "EdmSales vbSalesAndProfit",
        "toColumn": "Profit Center",
        "toTable": "EdmMasterData dProfitCenter"
      },
      {
        "name": "d6add865-7ee2-4999-9772-5b26bb1758cf",
        "fromColumn": "Material",
        "fromTable": "EdmSales vbSalesAndProfit",
        "toColumn": "Material",
        "toTable": "EdmMaterial dMaterial"
      },
      {
        "name": "4bc8090a-0b01-4a02-beca-019482234b70",
        "fromColumn": "LastRefresh",
        "fromTable": "Last Refreshed Date Time",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_f7b44c1a-a188-46de-b33c-be24e49e4e13"
      },
      {
        "name": "15b68b2f-da53-4464-9e43-1e4222011fcd",
        "fromColumn": "SoldTo Party",
        "fromTable": "EdmSales vbSalesAndProfit",
        "toColumn": "Sold To Customer",
        "toTable": "EdmCustomer dSoldToCustomer"
      },
      {
        "name": "6a91563a-8420-4e45-a81f-6d21edfe3256",
        "fromColumn": "ShipTo Party",
        "fromTable": "EdmSales vbSalesAndProfit",
        "toColumn": "Ship To Customer",
        "toTable": "EdmCustomer dShipToCustomer"
      },
      {
        "name": "7c955e84-923f-43ec-8087-391a967866b8",
        "fromColumn": "Final Destination Ctry",
        "fromTable": "EdmSales vbSalesAndProfit",
        "toColumn": "Country",
        "toTable": "EdmMasterData dCountry"
      },
      {
        "name": "3ca78ecf-685c-486a-94d9-6c1665682daf",
        "fromColumn": "Sales Org",
        "fromTable": "EdmSales vbSalesAndProfit",
        "toColumn": "Sales Org",
        "toTable": "EdmMasterData dSalesOrganisation"
      },
      {
        "name": "7cda6b27-28ca-4948-b3fc-50314199123e",
        "fromColumn": "BU Sls",
        "fromTable": "EdmSales vbSalesAndProfit",
        "toColumn": "BU",
        "toTable": "EdmMasterData dBusinessUnit"
      },
      {
        "name": "8525853b-c98d-49ac-b1e6-9108103ba7c6",
        "fromColumn": "Transport Mode",
        "fromTable": "EdmSales vbSalesAndProfit",
        "toColumn": "Transport Mode",
        "toTable": "EdmMasterData dTransportMode"
      },
      {
        "name": "510fec18-aebf-4027-bd6f-a0bfc2389a72",
        "fromColumn": "Sales Type",
        "fromTable": "EdmSales vbSalesAndProfit",
        "toColumn": "Sales Type",
        "toTable": "EdmMasterData dSalesType"
      },
      {
        "name": "6fd87581-0752-4b7c-aa83-79e4eb8a3690",
        "fromColumn": "Mkt End Use",
        "fromTable": "EdmSales vbSalesAndProfit",
        "toColumn": "Mkt End Use",
        "toTable": "EdmMasterData dMarketEndUse"
      },
      {
        "name": "0c5f25ac-f430-4e0f-948e-07d6beb28d13",
        "crossFilteringBehavior": "bothDirections",
        "fromCardinality": "one",
        "fromColumn": "Profitability Matrix Order",
        "fromTable": "Profitability Matrix",
        "toColumn": "PY CM1/SAVPM Margin Per Unit Order",
        "toTable": "PY CM1/SAVPM Margin Per Unit"
      },
      {
        "name": "73e69629-e646-4244-9407-072a3ec27aca",
        "crossFilteringBehavior": "bothDirections",
        "fromCardinality": "one",
        "fromColumn": "Profitability Matrix Order",
        "fromTable": "Profitability Matrix",
        "toColumn": "Profitability Matrix - PY Order",
        "toTable": "Profitability Matrix - PY"
      },
      {
        "name": "0cd193ad-3f55-48a1-9987-f5f83d0b8674",
        "fromColumn": "Final Destination Country",
        "fromTable": "EdmMasterData dCountry",
        "toColumn": "Country",
        "toTable": "Final Destination County Zone"
      },
      {
        "name": "2b04b207-b03c-4a3e-bd9a-5f41e47a5dae",
        "crossFilteringBehavior": "bothDirections",
        "fromCardinality": "one",
        "fromColumn": "Profitability Matrix - Running Order",
        "fromTable": "Profitability Matrix - YTD",
        "toColumn": "Profitability Matrix Order",
        "toTable": "Profitability Matrix"
      },
      {
        "name": "8c7a6bc4-4907-44b0-8fbe-1226e596ad50",
        "crossFilteringBehavior": "bothDirections",
        "fromCardinality": "one",
        "fromColumn": "Profitability Matrix Order",
        "fromTable": "Profitability Matrix",
        "toColumn": "Profitability Matrix - Running PY Order",
        "toTable": "Profitability Matrix - PY YTD"
      },
      {
        "name": "e9a2fa85-0ea3-4494-baed-b30e49d3b0fe",
        "crossFilteringBehavior": "bothDirections",
        "fromCardinality": "one",
        "fromColumn": "Profitability Matrix Order",
        "fromTable": "Profitability Matrix",
        "toColumn": "CM1/SAVPM Margin Per Unit Order",
        "toTable": "CM1/SAVPM Margin Per Unit"
      },
      {
        "name": "a41ed14a-044d-46d6-9bee-8f60ca2598aa",
        "crossFilteringBehavior": "bothDirections",
        "fromCardinality": "one",
        "fromColumn": "Profitability Matrix Order",
        "fromTable": "Profitability Matrix",
        "toColumn": "Top N Profitability Matrix Order",
        "toTable": "Top N Profitability Matrix"
      },
      {
        "name": "ab3aa60f-86ec-4e0c-a98d-5126e6fbd269",
        "crossFilteringBehavior": "bothDirections",
        "fromCardinality": "one",
        "fromColumn": "Profitability Matrix Order",
        "fromTable": "Profitability Matrix",
        "toColumn": "Top N Profitability Matrix - PY Order",
        "toTable": "Top N Profitability Matrix - PY"
      },
      {
        "name": "23aa1898-6c84-4f43-afd8-be732675766f",
        "fromColumn": "Top N CM1/SAVPM Margin Per Unit Order",
        "fromTable": "Top N CM1/SAVPM Margin Per Unit",
        "toColumn": "Profitability Matrix Order",
        "toTable": "Profitability Matrix"
      },
      {
        "name": "a919da49-179b-492c-a9ba-94ffa900ea00",
        "fromColumn": "Top N PY CM1/SAVPM Margin Per Unit Order",
        "fromTable": "Top N PY CM1/SAVPM Margin Per Unit",
        "toColumn": "Profitability Matrix Order",
        "toTable": "Profitability Matrix"
      }
    ],
    "roles": [
      {
        "name": "AD Group",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "7f89393dcd884d8c8a19e8e98e633a15"
          }
        ],
        "modelPermission": "read",
        "tablePermissions": [
          {
            "name": "Show/Hide"
          }
        ]
      },
      {
        "name": "Global Users",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "8ddd27e0a50141738e2d6cf790ed55ff"
          }
        ],
        "modelPermission": "read",
        "tablePermissions": [
          {
            "name": "Date Table",
            "filterExpression": "[Year] == 1900"
          },
          {
            "name": "Show/Hide"
          }
        ]
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "DateTableTemplate_eeb4c200-30bd-46ad-8481-d8f834d199b9",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "3ae50b58-90c4-4869-9ed3-75413d480265",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "0deecc53-4671-49ba-ae32-6f575da6a9ee",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "a80a2473-a51c-4c98-86a7-1ad470055019",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "6a28e372-bd75-44c4-bcba-684c1b7139d4",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "3bbbf96d-7545-4c29-aca5-d919700712a2",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "e2725ecf-2b7d-4f89-872d-2008f1c84365",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "43a4b1b3-ac9b-4a0d-be1c-3e1e003e8f03",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "43a2f087-eae0-4531-b4a2-84d6d82c43da",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "0e775ec3-a789-4dfb-a11b-33fd26f7d364",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "3b3c0141-f171-4781-bb13-db990b9fc847",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "c29332ef-750f-4698-a7e8-9683ad2890d7",
                "ordinal": 3
              }
            ],
            "lineageTag": "4197832e-c882-4379-9ccf-962aaf87d2ec"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "b42f7b54-4db3-44cd-9c85-c22a6bdc2d8f",
        "partitions": [
          {
            "name": "DateTableTemplate_eeb4c200-30bd-46ad-8481-d8f834d199b9-2f8a8b0d-1fa4-4242-b719-98a7e9d698bc",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Distribution Channel",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Distribution Channel",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b18aa418-a2a3-4f07-8fed-b77b38615905",
            "sourceColumn": "Distribution Channel",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "665c31bc-2baf-4e0a-a74f-3ca734cbabc0",
        "partitions": [
          {
            "name": "Distribution Channel-8ee3cf42-f94a-462e-b5e9-c7684dac050e",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "   Source = Value.NativeQuery(Snowflake.Databases(server,warehouse,[Role=role]){[Name=db]}[Data], \"SELECT DISTINCT \"\"Distribution Channel\"\" FROM \"&db&\".EDMSALES.\"\"vbSalesAndProfit\"\" \", null, [EnableFolding=true])",
                "in",
                "    Source",
                "",
                "",
                "/*",
                "let",
                "    Source = Sql.Database(\"lyb-sql-stgdacore-002.5bff9fcb8330.database.windows.net\", \"Source\", [Query=\"SELECT DISTINCT#(lf)[Distribution Channel]#(lf)FROM Edmsales.vbSalesAndProfit\", MultiSubnetFailover=true])",
                "in",
                "    Source",
                "*/"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Business Group",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Business Group",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8328b6e6-441c-414f-b405-fc9feb092a24",
            "sourceColumn": "Business Group",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "792f0822-cf77-45e9-a838-8e4af5244b01",
        "partitions": [
          {
            "name": "Business Group-ebcee7a8-9bb9-4f64-a5e9-0b9d1362075d",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "   Source = Value.NativeQuery(Snowflake.Databases(server,warehouse,[Role=role]){[Name=db]}[Data], \"SELECT DISTINCT \"\"Business Group\"\" FROM \"&db&\".EDMSALES.\"\"vbSalesAndProfit\"\" \", null, [EnableFolding=true])",
                "in",
                "    Source",
                "",
                "",
                "/*",
                "let",
                "    Source = Sql.Database(\"lyb-sql-stgdacore-002.5bff9fcb8330.database.windows.net\", \"Source\", [Query=\"SELECT DISTINCT#(lf)[Business Group]#(lf)FROM Edmsales.vbSalesAndProfit\", MultiSubnetFailover=true])",
                "in",
                "    Source",
                "*/"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "EdmSales vbSalesAndProfit",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "Market Manager",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "379d1d53-3cf7-4143-96a7-b4e18cea10b9",
            "sourceColumn": "Market Manager",
            "summarizeBy": "none"
          },
          {
            "name": "Plant",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "15847fe6-6f40-409b-9522-bd40640508c8",
            "sourceColumn": "Plant",
            "summarizeBy": "none"
          },
          {
            "name": "Package Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0054dfd2-c945-4a55-94c3-9adcc6401adc",
            "sourceColumn": "Package Type",
            "summarizeBy": "none"
          },
          {
            "name": "Export Indicator",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b7a58dae-e3d8-4917-aef2-a943d4c9dec7",
            "sourceColumn": "Export Indicator",
            "summarizeBy": "none"
          },
          {
            "name": "Distribution Channel",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9ea50f3e-293f-4308-9af1-64a3ddcc16ef",
            "sourceColumn": "Distribution Channel",
            "summarizeBy": "none"
          },
          {
            "name": "Company Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "dc73a6a4-f2f7-4135-8c50-e0a22c705ec7",
            "sourceColumn": "Company Code",
            "summarizeBy": "none"
          },
          {
            "name": "Profit Center",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bedd108e-bcb2-4084-ac0f-530f7d048fb7",
            "sourceColumn": "Profit Center",
            "summarizeBy": "none"
          },
          {
            "name": "Incoterms",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "37428092-98ae-4822-b8d6-b83b5f554c19",
            "sourceColumn": "Incoterms",
            "summarizeBy": "none"
          },
          {
            "name": "Vendor",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a3c18d7d-87b8-4ce9-a874-2439374c78cd",
            "sourceColumn": "Vendor",
            "summarizeBy": "none"
          },
          {
            "name": "Business Group",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bee584b6-c79f-4f90-9325-332d6c79bb3e",
            "sourceColumn": "Business Group",
            "summarizeBy": "none"
          },
          {
            "name": "COM Inv Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "644e6ece-fb8b-45b2-878b-3ee5353790b9",
            "sourceColumn": "COM Inv Date",
            "summarizeBy": "none"
          },
          {
            "name": "Division",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "edfce8a3-2f7a-4696-a746-dc414f0327a0",
            "sourceColumn": "Division",
            "summarizeBy": "none"
          },
          {
            "name": "Product Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c0531649-faee-4765-9c6f-5a3002908f13",
            "sourceColumn": "Product Code",
            "summarizeBy": "none"
          },
          {
            "name": "Material",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bf2967fd-2908-498d-8dd9-3b9196a834eb",
            "sourceColumn": "Material",
            "summarizeBy": "none"
          },
          {
            "name": "Product Hierarchy Level 3",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "091ef260-82fa-4127-a0a0-666d5fff76f7",
            "sourceColumn": "Product Hierarchy Level 3",
            "summarizeBy": "none"
          },
          {
            "name": "Mkt End Use Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fb8c3350-6cf4-434b-8fb3-63dda96652c7",
            "sourceColumn": "Mkt End Use Key",
            "summarizeBy": "none"
          },
          {
            "name": "Parent Company",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "beb6005d-8962-45b6-8cd2-9ddb41976672",
            "sourceColumn": "Parent Company",
            "summarizeBy": "none"
          },
          {
            "name": "SoldTo Party",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "83d4b839-cb7b-4bf8-8afc-6712a2d792d7",
            "sourceColumn": "SoldTo Party",
            "summarizeBy": "none"
          },
          {
            "name": "SoldTo City",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fb6bc3c6-e243-4a6c-9880-6231f9428f75",
            "sourceColumn": "SoldTo City",
            "summarizeBy": "none"
          },
          {
            "name": "SoldTo Country",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a395a861-9b1c-4b81-a5db-6339e7f06371",
            "sourceColumn": "SoldTo Country",
            "summarizeBy": "none"
          },
          {
            "name": "SoldTo Postal Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a6525fae-1419-429f-8fce-198d19ebca32",
            "sourceColumn": "SoldTo Postal Code",
            "summarizeBy": "none"
          },
          {
            "name": "SoldTo Region",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2b49e720-07a8-462d-aaa0-842ca30a1956",
            "sourceColumn": "SoldTo Region",
            "summarizeBy": "none"
          },
          {
            "name": "SoldTo Sales Rep",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b342e3d6-04f3-41a2-978f-9e7a4c63b545",
            "sourceColumn": "SoldTo Sales Rep",
            "summarizeBy": "none"
          },
          {
            "name": "ShipTo Party",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fd80862b-bba2-4bde-af00-f924134bd567",
            "sourceColumn": "ShipTo Party",
            "summarizeBy": "none"
          },
          {
            "name": "ShipTo City",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ef4e0076-c243-4df0-aec6-aff186a70fd6",
            "sourceColumn": "ShipTo City",
            "summarizeBy": "none"
          },
          {
            "name": "ShipTo Postal Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e69f6d9b-ced1-49ee-b053-62401e92e8d3",
            "sourceColumn": "ShipTo Postal Code",
            "summarizeBy": "none"
          },
          {
            "name": "ShipTo Region",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fd569a27-b354-4129-9baf-345feb8f9f8f",
            "sourceColumn": "ShipTo Region",
            "summarizeBy": "none"
          },
          {
            "name": "ShipTo Sales Rep",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "33fe17c4-a358-43be-9436-6bf224d685d3",
            "sourceColumn": "ShipTo Sales Rep",
            "summarizeBy": "none"
          },
          {
            "name": "Division Grp",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "716df7cb-f346-4610-a4a5-e591bad2f321",
            "sourceColumn": "Division Grp",
            "summarizeBy": "none"
          },
          {
            "name": "Shipping Condition",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "addc06c4-8008-4a4a-865a-4aac11406f75",
            "sourceColumn": "Shipping Condition",
            "summarizeBy": "none"
          },
          {
            "name": "Sales Org",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d0c91a65-ce9f-47dd-8885-d1bd695bf003",
            "sourceColumn": "Sales Org",
            "summarizeBy": "none"
          },
          {
            "name": "Com Invoice YearMonth",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "786ea864-34c1-4a6f-93b4-d6991cecae3f",
            "sourceColumn": "Com Invoice YearMonth",
            "summarizeBy": "none"
          },
          {
            "name": "Sales Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a5f3100d-4613-4960-899b-5f586004b566",
            "sourceColumn": "Sales Type",
            "summarizeBy": "none"
          },
          {
            "name": "Transport Mode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bddf4823-611c-4239-811a-7346a7509545",
            "sourceColumn": "Transport Mode",
            "summarizeBy": "none"
          },
          {
            "name": "Mkt End Use",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7c32a9ef-7a3a-483c-91f7-f16fbb8d7d71",
            "sourceColumn": "Mkt End Use",
            "summarizeBy": "none"
          },
          {
            "name": "BU Sls",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7d3f206c-b495-4316-9cac-4e13a2dd5b5a",
            "sourceColumn": "BU Sls",
            "summarizeBy": "none"
          },
          {
            "name": "Mkt Seg",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4b4569b9-2025-4e44-874b-740cf84388a8",
            "sourceColumn": "Mkt Seg",
            "summarizeBy": "none"
          },
          {
            "name": "Final Destination Ctry",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "33c9439e-10c2-43d7-9a4b-9cfce170fc43",
            "sourceColumn": "Final Destination Ctry",
            "summarizeBy": "none"
          },
          {
            "name": "Actual Quantity LBS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "4104fd31-eb07-4fa4-9c2e-c6882b1fb06b",
            "sourceColumn": "Actual Quantity LBS",
            "summarizeBy": "sum"
          },
          {
            "name": "Adj Net Invoice Price EUR",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "f79842d3-4e88-4819-bca9-21fcdcc40652",
            "sourceColumn": "Adj Net Invoice Price EUR",
            "summarizeBy": "sum"
          },
          {
            "name": "Adj Net Invoice Price USD",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "906849de-8d45-425c-ba5f-49b3b5e12db6",
            "sourceColumn": "Adj Net Invoice Price USD",
            "summarizeBy": "sum"
          },
          {
            "name": "Cost Of Cnsgn Basis EUR",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "b64f5566-6085-45d8-ba55-cecccfd9823f",
            "sourceColumn": "Cost Of Cnsgn Basis EUR",
            "summarizeBy": "sum"
          },
          {
            "name": "Cost Of Cnsgn Basis USD",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "7f142e47-1f2e-4260-80f9-f3fae340fbc7",
            "sourceColumn": "Cost Of Cnsgn Basis USD",
            "summarizeBy": "sum"
          },
          {
            "name": "Freight Amount EUR",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "f3335078-93ca-4ad7-ac12-02b998e1788b",
            "sourceColumn": "Freight Amount EUR",
            "summarizeBy": "sum"
          },
          {
            "name": "Freight Amount USD",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "d96b8f87-c5c1-4aa0-a616-db5bb2a6bb9b",
            "sourceColumn": "Freight Amount USD",
            "summarizeBy": "sum"
          },
          {
            "name": "Open Order Qty LBS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "c5f488a2-882f-417c-9b5d-c17763c8f46f",
            "sourceColumn": "Open Order Qty LBS",
            "summarizeBy": "sum"
          },
          {
            "name": "Delivered Not Invoiced Qty LBS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "748a976a-4b83-4ab0-bf7b-cdef274eac48",
            "sourceColumn": "Delivered Not Invoiced Qty LBS",
            "summarizeBy": "sum"
          },
          {
            "name": "Payment Terms EUR",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "20b2cf9a-fa00-4b85-9662-b2fde3efd42b",
            "sourceColumn": "Payment Terms EUR",
            "summarizeBy": "sum"
          },
          {
            "name": "Payment Terms USD",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "1f63e248-e49a-46f8-a8c8-2d9c7772eec7",
            "sourceColumn": "Payment Terms USD",
            "summarizeBy": "sum"
          },
          {
            "name": "Plan Quantity LBS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "0be38e8b-a8a8-4fc0-bfe3-ee8f3f641ff0",
            "sourceColumn": "Plan Quantity LBS",
            "summarizeBy": "sum"
          },
          {
            "name": "SAVPM Amount EUR",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "e618b781-2ba5-4c9f-b367-d7ffd3be2770",
            "sourceColumn": "SAVPM Amount EUR",
            "summarizeBy": "sum"
          },
          {
            "name": "SAVPM Amount USD",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "a3b685b0-5528-492b-8f6f-8fb98deb77b6",
            "sourceColumn": "SAVPM Amount USD",
            "summarizeBy": "sum"
          },
          {
            "name": "CM1 Amount EUR",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "c3317e34-d857-4bae-97f2-9dc92c16f4ae",
            "sourceColumn": "CM1 Amount EUR",
            "summarizeBy": "sum"
          },
          {
            "name": "CM1 Amount USD",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "a01f988f-6777-4f66-9ad7-39852f9ae359",
            "sourceColumn": "CM1 Amount USD",
            "summarizeBy": "sum"
          },
          {
            "name": "Com Invoice Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "348e8e87-c224-4e6c-a5c3-2d22cbba4def",
            "sourceColumn": "Com Invoice Date",
            "summarizeBy": "none"
          },
          {
            "name": "SoldTo Sales Rep Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8b2fe492-4177-4373-acf2-20523b048ba0",
            "sourceColumn": "SoldTo Sales Rep Name",
            "summarizeBy": "none"
          },
          {
            "name": "Market Manager Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "01d322b4-ab69-4856-bfce-85cd88eed0f9",
            "sourceColumn": "Market Manager Name",
            "summarizeBy": "none"
          },
          {
            "name": "Mkt Seg Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f44142cc-ed9d-4b70-92e8-5f943477c5bc",
            "sourceColumn": "Mkt Seg Name",
            "summarizeBy": "none"
          },
          {
            "name": "Version",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "29e0ce8e-7cc3-4fb8-b01c-3a0803cc3e6d",
            "sourceColumn": "Version",
            "summarizeBy": "none"
          },
          {
            "name": "Version Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9b77122b-169e-4ed7-86ae-1973eeeb9d00",
            "sourceColumn": "Version Name",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "4dce9a22-bed2-43bd-9d64-e89fccd3a9f7",
        "partitions": [
          {
            "name": "EdmSales vbSalesAndProfit-f5398329-b1c1-4c21-80b3-9d7e30f0e9ce",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "",
                "    Source = Value.NativeQuery(Snowflake.Databases(server,warehouse,[Role=role]){[Name=db]}[Data], \"SELECT \"\"Parent Company\"\", \"\"SoldTo Party\"\",\"\"SoldTo City\"\", \"\"SoldTo Country\"\",  \"\"SoldTo Postal Code\"\", \"\"SoldTo Region\"\",  \"\"SoldTo Sales Rep\"\",\"\"SoldTo Sales Rep Name\"\", \"\"ShipTo Party\"\",\"\"ShipTo City\"\",\"\"ShipTo Postal Code\"\", \"\"ShipTo Region\"\",\"\"ShipTo Sales Rep\"\", \"\"Market Manager\"\",\"\"Market Manager Name\"\", \"\"Division Grp\"\",\"\"Division\"\", \"\"Product Code\"\",\"\"Material\"\",\"\"Product Hierarchy Level 3\"\", \"\"Shipping Condition\"\", \"\"Plant\"\", \"\"Sales Org\"\", \"\"Com Invoice YearMonth\"\", \"\"Sales Type\"\", \"\"Package Type\"\", \"\"Export Indicator\"\", \"\"Distribution Channel\"\", \"\"Transport Mode\"\", \"\"Company Code\"\", \"\"Profit Center\"\", \"\"Mkt End Use Key\"\",\"\"Mkt End Use\"\", \"\"Business Group\"\", \"\"BU Sls\"\", \"\"Mkt Seg\"\",\"\"Mkt Seg Name\"\", \"\"Incoterms\"\", \"\"Vendor\"\", \"\"Final Destination Ctry\"\", \"\"Actual Quantity LBS\"\", \"\"Adj Net Invoice Price EUR\"\", \"\"Adj Net Invoice Price USD\"\", \"\"Cost Of Cnsgn Basis EUR\"\", \"\"Cost Of Cnsgn Basis USD\"\", \"\"Freight Amount EUR\"\", \"\"Freight Amount USD\"\", \"\"Open Order Qty LBS\"\", \"\"Delivered Not Invoiced Qty LBS\"\", \"\"Payment Terms EUR\"\", \"\"Payment Terms USD\"\", \"\"Plan Quantity LBS\"\", \"\"SAVPM Amount EUR\"\", \"\"SAVPM Amount USD\"\", \"\"CM1 Amount EUR\"\", \"\"CM1 Amount USD\"\", \"\"Com Invoice Date\"\", \"\"Version\"\", \"\"Version Name\"\" FROM \"&db&\".EDMSALES.\"\"vbSalesAndProfit\"\" WHERE \"\"Version\"\" = ''\", null, [EnableFolding=true]),",
                "/*",
                "    Source = Sql.Database(\"lyb-sql-stgdacore-002.5bff9fcb8330.database.windows.net\", \"Source\", [Query=\"SELECT#(lf)[Parent Company],#(lf)[SoldTo Party],[SoldTo City], [SoldTo Country], #(lf)[SoldTo Postal Code], [SoldTo Region], #(lf)[SoldTo Sales Rep],[SoldTo Sales Rep Name],#(lf)[ShipTo Party],[ShipTo City],[ShipTo Postal Code],#(lf)[ShipTo Region],[ShipTo Sales Rep],#(lf)[Market Manager],[Market Manager Name],#(lf)[Division Grp],[Division],#(lf)[Product Code],[Material],[Product Hierarchy Level 3],#(lf)[Shipping Condition],#(lf)[Plant],#(lf)[Sales Org],#(lf)[Com Invoice YearMonth],#(lf)[Sales Type],#(lf)[Package Type],#(lf)[Export Indicator],#(lf)[Distribution Channel],#(lf)[Transport Mode],#(lf)[Company Code],#(lf)[Profit Center],#(lf)[Mkt End Use Key],[Mkt End Use],#(lf)[Business Group],#(lf)[BU Sls],#(lf)[Mkt Seg],[Mkt Seg Name],#(lf)[Incoterms],#(lf)[Vendor],#(lf)[Final Destination Ctry],#(lf)[Actual Quantity LBS],#(lf)[Adj Net Invoice Price EUR],#(lf)[Adj Net Invoice Price USD],#(lf)[Cost Of Cnsgn Basis EUR],#(lf)[Cost Of Cnsgn Basis USD],#(lf)[Freight Amount EUR],#(lf)[Freight Amount USD],#(lf)[Open Order Qty LBS],#(lf)[Delivered Not Invoiced Qty LBS],#(lf)[Payment Terms EUR],#(lf)[Payment Terms USD],#(lf)[Plan Quantity LBS],#(lf)[SAVPM Amount EUR],#(lf)[SAVPM Amount USD],#(lf)[CM1 Amount EUR],#(lf)[CM1 Amount USD],#(lf)[Com Invoice Date],#(lf)[Version],#(lf)[Version Name]#(lf)FROM EdmSales.vbSalesAndProfit#(lf)WHERE [Version] = ''\", MultiSubnetFailover=true, CommandTimeout=#duration(0, 1, 30, 0)]),",
                "*/",
                "    #\"Added Custom Column\" = Table.AddColumn(Source, \"COM Inv Date\", each Text.Combine({Text.Middle([#\"Com Invoice YearMonth\"], 4), \"/01/\", Text.Start([#\"Com Invoice YearMonth\"], 4)})),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Added Custom Column\",{{\"COM Inv Date\", type date}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Date Table",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "2792dccf148a4ea28df21901f98497f3"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              },
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "a1feacf2-d40d-4f17-ae16-d56a4673ad90",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_a3e90990-2659-4fbc-a79d-2683b663011e"
                },
                "isDefault": true,
                "relationship": "2d0653a7-2d62-4d7c-8460-729ef57db08c"
              }
            ]
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "YEAR('Date Table'[Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "e16e09b9-804e-44b7-bc42-f97503ab6e4d",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "MONTH('Date Table'[Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "b7d54032-fc61-48f4-b7c9-3171db2f15fa",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Month Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "FORMAT('Date Table'[Date],\"mmm\")",
            "isDataTypeInferred": true,
            "lineageTag": "3d6c66b2-79c4-4b60-b333-d1e71834429d",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Todays Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              },
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "expression": "TODAY()",
            "formatString": "Short Date",
            "isDataTypeInferred": true,
            "lineageTag": "1101807a-41d4-4fd2-a751-0cb4b2d4138f",
            "summarizeBy": "none",
            "type": "calculated",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_8e68eb8c-b300-45b5-9474-1d794476bef1"
                },
                "isDefault": true,
                "relationship": "04ff5f92-8636-4ef5-b9cf-3535722bdc7a"
              }
            ]
          },
          {
            "name": "Max Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              },
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "expression": "MAX('Date Table'[Date])",
            "formatString": "Short Date",
            "isDataTypeInferred": true,
            "lineageTag": "afe735d0-9c98-4641-95d2-2f2404601ff5",
            "summarizeBy": "none",
            "type": "calculated",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_4b4b43bf-cb33-40ba-8d24-f0de07093abd"
                },
                "isDefault": true,
                "relationship": "6c48537e-3308-4526-9fdd-8e8bee6446ca"
              }
            ]
          },
          {
            "name": "Current Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "VAR MAX_YEAR = YEAR('Date Table'[Max Date])",
              "Return if('Date Table'[Year]=MAX_YEAR,\"Current Year\")"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "bcf6ae67-5bfd-4783-b5ea-987beb30751b",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Current Year(Todays)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "VAR MAX_YEAR = YEAR('Date Table'[Todays Date])",
              "Return if('Date Table'[Year]=MAX_YEAR,\"Current Year\")"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "86d940a3-fb0f-454c-b7ff-b92c0d68fb33",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Previous Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "VAR MAX_YEAR = YEAR('Date Table'[Max Date])-1",
              "Return if('Date Table'[Year]=MAX_YEAR,\"Previous Year\")"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "a40c5f66-16f8-47b3-bd1f-c975ce2456f9",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Previous Year(Todays)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "VAR MAX_YEAR = YEAR('Date Table'[Todays Date])-1",
              "Return if('Date Table'[Year]=MAX_YEAR,\"Previous Year\")"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "7c9ba9db-22be-4f88-b235-6c582925103d",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "SEPARATION",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "",
              "var Y = year(TODAY())",
              "",
              "var M = MONTH(TODAY())",
              "",
              "return",
              "",
              "IF([YEAR]=Y && [Month]=M, \"PRESENT\",",
              "IF([YEAR]<Y || ([YEAR]=Y && [Month]<M) , \"PAST\",",
              "\"FUTURE\"",
              "))"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "49e3ba81-7af9-4bb4-b9fb-d045d012d5cb",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MONTH TYPE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "",
              "VAR M = VALUE('Date Table'[Month])",
              "",
              "RETURN ",
              "",
              "IF(",
              "    M=MONTH(TODAY()),\"CURRENT\",",
              "    IF(",
              "        M<MONTH(TODAY()),\"PAST\",",
              "        IF(",
              "            M>MONTH(TODAY()),\"FUTURE\",",
              "            \"INCORRECT\"",
              "        )))"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "47a7f49a-a8da-42ef-bfce-c40920d6ef97",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "WITHIN MAX MONTH",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "",
              "",
              "VAR MAXM= ",
              "        CALCULATE(MAX('Date Table'[Month]),ALL('Date Table'))",
              "",
              "VAR M = VALUE('Date Table'[Month])",
              "",
              "",
              "RETURN",
              "",
              "IF(",
              "    M<=MAXM,",
              "    \"Y\",\"N\"",
              ")"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "4da088fb-4335-49d2-b767-eb010aa9fdb2",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Year Qtr",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "var QTR = QUARTER('Date Table'[Date])",
              "Return CONCATENATE(\"Q \",CONCATENATE(QTR,CONCATENATE(\" \",'Date Table'[Year])))"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "09dda453-a356-4bd5-a839-a59f8c4fd551",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Year Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "var Monthname = ('Date Table'[Month Name])",
              "Return CONCATENATE(Monthname,CONCATENATE(\" \",'Date Table'[Year]))"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "785b5098-48b5-4f43-b4ba-1c82d0a339b7",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Prior Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "YEAR('Date Table'[Date])-1",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "b809bc7e-85ff-4058-9659-b2cc5534ab10",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Last three year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "if('Date Table'[Year]<=YEAR(today())",
              "&& 'Date Table'[Year] >= year(today()) -2,",
              "\"Last Three Year\",",
              "\"Blank\"",
              ")"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "d8f3b486-301a-4b7e-8b75-64492d312e86",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "f801e3a4-761e-4b1f-ac4a-8e92dd1d7b4c",
        "partitions": [
          {
            "name": "Date Table-2bf1432b-9521-4d2d-9a50-0b63a655bb51",
            "mode": "import",
            "source": {
              "expression": "CALENDAR(min('EdmSales vbSalesAndProfit'[COM Inv Date]),max('EdmSales vbSalesAndProfit'[COM Inv Date]))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_a3e90990-2659-4fbc-a79d-2683b663011e",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "5f74329e-abef-425e-ad3f-f9bdf0221731",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "279f8bc8-1237-49c4-b3e8-f635b65c584d",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "57cedff1-7a86-4ba6-b293-34f2226e6d47",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "ec24756d-0e8f-42b5-9b6a-e8cceba9e3d5",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "a80a95dd-76af-4e8b-9da3-4a47f4d234c4",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "b772dabd-992c-4a1b-9984-099912267e1e",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "3c72b9aa-d3db-4272-a6e3-4361aaacef40",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "2a0019f8-9fdc-45b7-8006-33ca8f2a946c",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "ca878263-cedb-4d68-8beb-9d631ac8a6ce",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "a12311ec-c4d8-4470-92dd-fcab125ec2c1",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "49c88b1b-311c-4085-8a4d-80bd435dd2fd",
                "ordinal": 3
              }
            ],
            "lineageTag": "6f3a6653-5097-4689-8811-37df8c913d97"
          }
        ],
        "isHidden": true,
        "lineageTag": "52120607-7920-4d91-a925-5fd4bbbed2c5",
        "partitions": [
          {
            "name": "LocalDateTable_a3e90990-2659-4fbc-a79d-2683b663011e-40983b30-517a-40ae-8911-d2133bf15be0",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Date Table'[Date])), 1, 1), Date(Year(MAX('Date Table'[Date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_8e68eb8c-b300-45b5-9474-1d794476bef1",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "c044e2ff-993a-4738-bd26-21b34e05a231",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "36a13b30-95b9-4414-92c7-57c75d4072d0",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "6548f61b-85e5-4d8b-a1e4-399b9059a06d",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "5954b6cb-0fd7-4378-b15b-1f145bfb5c88",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "20704dd3-c9ef-4799-adc9-c323c49c43a9",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "2076e4ba-a726-4a37-b4e2-4f3697868a21",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "5ac71eb4-c69b-46c2-8f81-98543a289308",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "f93ee2da-7b66-4454-9101-16a9346d8160",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "6e787fa6-c8ef-44f1-a91d-e8ba3042587c",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "242f6269-b9aa-439e-a0eb-82b6e341f42e",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "5ad09cea-c262-406e-9404-5ac33c09cafb",
                "ordinal": 3
              }
            ],
            "lineageTag": "d20404f0-d56a-45c9-ab83-1eb182ed9e8a"
          }
        ],
        "isHidden": true,
        "lineageTag": "ee2d4186-127f-4663-bed6-b88f1ecdd90e",
        "partitions": [
          {
            "name": "LocalDateTable_8e68eb8c-b300-45b5-9474-1d794476bef1-c0911a6f-8c7a-4e18-90cb-e0cf9b1f5eec",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Date Table'[Todays Date])), 1, 1), Date(Year(MAX('Date Table'[Todays Date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_4b4b43bf-cb33-40ba-8d24-f0de07093abd",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "4deaf366-26eb-4870-af9f-40b1257529d2",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "3f1982e4-502c-4a83-adbd-d8cbea403815",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "cf4228e4-44fe-4177-80a2-d7e54eeaa2b0",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "ea3906e1-df2f-44c5-a24b-4a498a3df057",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "ca7fbb4b-5864-4912-9dba-d309ad524c75",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "3272a492-04e6-4ec7-8fe1-1cd2ee7e565f",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "afc4930d-27a0-4e03-8dc0-f9e964e09f44",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "1c3eda30-1eb0-4f4d-8e82-7e0075ea023e",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "f61db589-8c07-4154-9a7b-62b91702f4c1",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "0ad84bb6-2f2e-42d6-8173-20f6e6e90f32",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "f787c148-29ae-43a0-866d-7f688d56b162",
                "ordinal": 3
              }
            ],
            "lineageTag": "43ab67b8-acf6-43e3-9a03-3ff0c2c03872"
          }
        ],
        "isHidden": true,
        "lineageTag": "599c036d-eaa4-4b98-bd1a-171ed453ef90",
        "partitions": [
          {
            "name": "LocalDateTable_4b4b43bf-cb33-40ba-8d24-f0de07093abd-3ce1569d-368f-4757-a31b-78bdc85a8292",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Date Table'[Max Date])), 1, 1), Date(Year(MAX('Date Table'[Max Date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "EdmMasterData dConversion",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "skConversion",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "bc6d3aea-347a-460f-94f9-c370da94f708",
            "sourceColumn": "skConversion",
            "summarizeBy": "sum"
          },
          {
            "name": "From UoM",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "c1b5fe20-f63b-4a87-89e3-edf28f1d4be3",
            "sourceColumn": "From UoM",
            "summarizeBy": "none"
          },
          {
            "name": "From UoM Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "177b5b1a-daa5-4861-9054-219c905fba45",
            "sourceColumn": "From UoM Name",
            "summarizeBy": "none"
          },
          {
            "name": "To UoM",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7feb0687-3334-4870-95bd-9f68eeca9ed2",
            "sourceColumn": "To UoM",
            "summarizeBy": "none"
          },
          {
            "name": "To UoM Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "ea409ba2-1333-4636-91da-505a6378f78c",
            "sourceColumn": "To UoM Name",
            "summarizeBy": "none"
          },
          {
            "name": "Multiplier",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "b9a973f3-2bd5-41b6-bed1-5b8a1aa69e90",
            "sourceColumn": "Multiplier",
            "summarizeBy": "sum"
          },
          {
            "name": "Comment",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "1d423126-340b-42f9-ae1d-cc43c7dd196e",
            "sourceColumn": "Comment",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "1a25527a-3423-48c5-8b0f-662711b9d9a0",
        "partitions": [
          {
            "name": "EdmMasterData dConversion-7db963b3-cac3-4b78-89ae-42592600982c",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "",
                "/*",
                "    Source = Sql.Database(\"lyb-sql-stgdacore-002.5bff9fcb8330.database.windows.net\", \"Source\", [MultiSubnetFailover=true]),",
                "    EdmMasterData_dConversion = Source{[Schema=\"EdmMasterData\",Item=\"vdConversion\"]}[Data],",
                "*/",
                "    Source = Snowflake.Databases(server,warehouse,[Role=role]),",
                "    DEV_SOURCE_Database = Source{[Name=db,Kind=\"Database\"]}[Data],",
                "    EDMMASTERDATA_Schema = DEV_SOURCE_Database{[Name=\"EDMMASTERDATA\",Kind=\"Schema\"]}[Data],",
                "    EdmMasterData_dConversion = EDMMASTERDATA_Schema{[Name=\"vdConversion\",Kind=\"View\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(EdmMasterData_dConversion, each ([From UoM] = \"LBS\"))",
                "in",
                "    #\"Filtered Rows\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Units Conversion",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Units ",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "63b3a9dc-57e0-4cc6-9c0c-cbbe5f573207",
            "sourceColumn": "Units ",
            "summarizeBy": "none"
          },
          {
            "name": "Multiplier",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "7efc0992-2bcc-4e93-9168-8f03c9cd3b1c",
            "sourceColumn": "Multiplier",
            "summarizeBy": "sum"
          },
          {
            "name": "Unit Suffix",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e7f05299-2dad-4664-afef-c55ddc21a7ad",
            "sourceColumn": "Unit Suffix",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "6d916ded-8179-42e2-bfbb-8ad943a86fcd",
        "partitions": [
          {
            "name": "Units Conversion-c76e52d7-0193-4ea3-aa8c-bfa43df9ee2e",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WcszJUQjNyywpVtJRMgRit9KcHKVYnWgl30zPnMz8PLC4ARgAWb6+YLmQjPzS4sS8FJgkSEYpNhYA\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#\"Units \" = _t, Multiplier = _t, #\"Unit Suffix\" = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Units \", type text}, {\"Multiplier\", Int64.Type}, {\"Unit Suffix\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Measures Table",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Column1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "8e39921c-e1eb-49c3-931c-b57c6483b043",
            "sourceColumn": "Column1",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "bf1b9a2d-7d12-42b4-8e7c-fee6f9070991",
        "measures": [
          {
            "name": "Planned Quantity",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "SUMX('EdmSales vbSalesAndProfit',[Plan Quantity LBS]*[UoM Multiplier])/[Units Multiplier]",
            "lineageTag": "d61bec7f-b456-443c-bada-848a562f777a"
          },
          {
            "name": "UoM Multiplier",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "SUMX('EdmMasterData dConversion',[Multiplier])",
            "lineageTag": "31f7bbd0-c736-4980-932c-b733439b0a44"
          },
          {
            "name": "Units Multiplier",
            "expression": "SUMX('Units Conversion',[Multiplier])",
            "formatString": "0",
            "lineageTag": "775180c5-65ee-405e-bc1e-d66a17156ba7"
          },
          {
            "name": "Actual Quantity",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "ROUND(SUMX('EdmSales vbSalesAndProfit',[Actual Quantity LBS]*[UoM Multiplier])/[Units Multiplier],5)",
            "formatString": "#,0.00",
            "lineageTag": "e3bdc115-b60b-41e8-8fae-fd5f426935a5"
          },
          {
            "name": "Current Year Invoiced",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "//NON-C ACTUAL QUANTITY",
              "",
              "VAR SAQ = CALCULATE(SUM('EdmSales vbSalesAndProfit'[Actual Quantity LBS])",
              "    , FILTER('EdmSales vbSalesAndProfit',[Actual Quantity LBS]<>0 && 'EdmSales vbSalesAndProfit'[Actual Quantity LBS]<>BLANK())",
              "    , FILTER('Date Table','Date Table'[SEPARATION]=\"PAST\"))",
              "",
              "VAR AQ = (SAQ*[UoM Multiplier])/[Units Multiplier]",
              "",
              "",
              "//NON-C OPEN ORDER VOLUME ",
              "",
              "VAR SOOQ = CALCULATE(SUM('EdmSales vbSalesAndProfit'[Open Order Qty LBS])",
              "     , FILTER('EdmSales vbSalesAndProfit',[Actual Quantity LBS]<>0 && 'EdmSales vbSalesAndProfit'[Actual Quantity LBS]<>BLANK())",
              "    , FILTER('Date Table','Date Table'[SEPARATION]=\"PAST\"))",
              "",
              "VAR OOQ = (SOOQ*[UoM Multiplier])/[Units Multiplier]",
              "",
              "//NON-C DELIVERED NOT INVOICED VOLUME ",
              "",
              "",
              "VAR SDNI = CALCULATE(SUM('EdmSales vbSalesAndProfit'[Delivered Not Invoiced Qty LBS])",
              "     , FILTER('EdmSales vbSalesAndProfit',[Actual Quantity LBS]<>0 && 'EdmSales vbSalesAndProfit'[Actual Quantity LBS]<>BLANK())",
              "    , FILTER('Date Table','Date Table'[SEPARATION]=\"PAST\"))",
              "",
              "VAR DNI = (SDNI*[UoM Multiplier])/[Units Multiplier]",
              "",
              "//RESULT",
              "",
              "RETURN",
              "",
              "AQ + OOQ + DNI"
            ],
            "lineageTag": "590dc613-b35e-4378-873f-ff36226a824c"
          },
          {
            "name": "Open Order Quantity",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "SUMX('EdmSales vbSalesAndProfit',[Open Order Qty LBS]*[UoM Multiplier])/[Units Multiplier]",
            "lineageTag": "c0b5106a-91db-4153-9dbd-6d48f02b7c73"
          },
          {
            "name": "Delivered not Invoiced Quantity",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "SUMX('EdmSales vbSalesAndProfit',[Delivered Not Invoiced Qty LBS]*[UoM Multiplier])/[Units Multiplier]",
            "lineageTag": "49ce7c2c-2f7e-47b9-9e03-0633be060928"
          },
          {
            "name": "Current Year Open",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "//NON-C ACTUAL QUANTITY",
              "",
              "//NON-C ACTUAL QUANTITY",
              "",
              "VAR SAQ = CALCULATE(SUM('EdmSales vbSalesAndProfit'[Actual Quantity LBS])",
              "    , FILTER('EdmSales vbSalesAndProfit',[Actual Quantity LBS]=0 || 'EdmSales vbSalesAndProfit'[Actual Quantity LBS]=BLANK())",
              "    , FILTER('Date Table','Date Table'[SEPARATION]=\"PAST\"))",
              "",
              "VAR AQ = (SAQ*[UoM Multiplier])/[Units Multiplier]",
              "",
              "",
              "//NON-C OPEN ORDER VOLUME ",
              "",
              "VAR SOOQ = CALCULATE(SUM('EdmSales vbSalesAndProfit'[Open Order Qty LBS])",
              "     , FILTER('EdmSales vbSalesAndProfit',[Actual Quantity LBS]=0 || 'EdmSales vbSalesAndProfit'[Actual Quantity LBS]=BLANK())",
              "    , FILTER('Date Table','Date Table'[SEPARATION]=\"PAST\"))",
              "",
              "VAR OOQ = (SOOQ*[UoM Multiplier])/[Units Multiplier]",
              "",
              "//NON-C DELIVERED NOT INVOICED VOLUME ",
              "",
              "",
              "VAR SDNI = CALCULATE(SUM('EdmSales vbSalesAndProfit'[Delivered Not Invoiced Qty LBS])",
              "     , FILTER('EdmSales vbSalesAndProfit',[Actual Quantity LBS]=0 || 'EdmSales vbSalesAndProfit'[Actual Quantity LBS]=BLANK())",
              "    , FILTER('Date Table','Date Table'[SEPARATION]=\"PAST\"))",
              "",
              "VAR DNI = (SDNI*[UoM Multiplier])/[Units Multiplier]",
              "",
              "//RESULT",
              "",
              "RETURN",
              "",
              "AQ + OOQ + DNI"
            ],
            "lineageTag": "151aa1d7-45d5-4d70-a356-99f515f415f1"
          },
          {
            "name": "Current Invoiced",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "//NON-C ACTUAL QUANTITY",
              "",
              "VAR SAQ = CALCULATE(SUM('EdmSales vbSalesAndProfit'[Actual Quantity LBS])",
              "    , FILTER('EdmSales vbSalesAndProfit',[Actual Quantity LBS]<>0 && 'EdmSales vbSalesAndProfit'[Actual Quantity LBS]<>BLANK())",
              "    , FILTER('Date Table','Date Table'[SEPARATION]<>\"PAST\"))",
              "",
              "VAR AQ = (SAQ*[UoM Multiplier])/[Units Multiplier]",
              "",
              "",
              "//NON-C OPEN ORDER VOLUME ",
              "",
              "VAR SOOQ = CALCULATE(SUM('EdmSales vbSalesAndProfit'[Open Order Qty LBS])",
              "     , FILTER('EdmSales vbSalesAndProfit',[Actual Quantity LBS]<>0 && 'EdmSales vbSalesAndProfit'[Actual Quantity LBS]<>BLANK())",
              "    , FILTER('Date Table','Date Table'[SEPARATION]<>\"PAST\"))",
              "",
              "VAR OOQ = (SOOQ*[UoM Multiplier])/[Units Multiplier]",
              "",
              "//NON-C DELIVERED NOT INVOICED VOLUME ",
              "",
              "",
              "VAR SDNI = CALCULATE(SUM('EdmSales vbSalesAndProfit'[Delivered Not Invoiced Qty LBS])",
              "     , FILTER('EdmSales vbSalesAndProfit',[Actual Quantity LBS]<>0 && 'EdmSales vbSalesAndProfit'[Actual Quantity LBS]<>BLANK())",
              "    , FILTER('Date Table','Date Table'[SEPARATION]<>\"PAST\"))",
              "",
              "VAR DNI = (SDNI*[UoM Multiplier])/[Units Multiplier]",
              "",
              "//RESULT",
              "",
              "RETURN",
              "",
              "AQ + OOQ + DNI"
            ],
            "lineageTag": "bf08ce5e-be7d-42d3-abba-1986d1dd20d1"
          },
          {
            "name": "Current Open",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "//NON-C ACTUAL QUANTITY",
              "",
              "//NON-C ACTUAL QUANTITY",
              "",
              "VAR SAQ = CALCULATE(SUM('EdmSales vbSalesAndProfit'[Actual Quantity LBS])",
              "    , FILTER('EdmSales vbSalesAndProfit',[Actual Quantity LBS]=0 || 'EdmSales vbSalesAndProfit'[Actual Quantity LBS]=BLANK())",
              "    , FILTER('Date Table','Date Table'[SEPARATION]<>\"PAST\"))",
              "",
              "VAR AQ = (SAQ*[UoM Multiplier])/[Units Multiplier]",
              "",
              "",
              "//NON-C OPEN ORDER VOLUME ",
              "",
              "VAR SOOQ = CALCULATE(SUM('EdmSales vbSalesAndProfit'[Open Order Qty LBS])",
              "     , FILTER('EdmSales vbSalesAndProfit',[Actual Quantity LBS]=0 || 'EdmSales vbSalesAndProfit'[Actual Quantity LBS]=BLANK())",
              "    , FILTER('Date Table','Date Table'[SEPARATION]<>\"PAST\"))",
              "",
              "VAR OOQ = (SOOQ*[UoM Multiplier])/[Units Multiplier]",
              "",
              "//NON-C DELIVERED NOT INVOICED VOLUME ",
              "",
              "",
              "VAR SDNI = CALCULATE(SUM('EdmSales vbSalesAndProfit'[Delivered Not Invoiced Qty LBS])",
              "     , FILTER('EdmSales vbSalesAndProfit',[Actual Quantity LBS]=0 || 'EdmSales vbSalesAndProfit'[Actual Quantity LBS]=BLANK())",
              "    , FILTER('Date Table','Date Table'[SEPARATION]<>\"PAST\"))",
              "",
              "VAR DNI = (SDNI*[UoM Multiplier])/[Units Multiplier]",
              "",
              "//RESULT",
              "",
              "RETURN",
              "",
              "AQ + OOQ + DNI"
            ],
            "lineageTag": "6834ce7e-2669-4c9f-a3b5-eedd3aa81e62"
          },
          {
            "name": "CM1",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "VAR Select_Currency = SELECTEDVALUE('Currency'[Currency])",
              "VAR CM1 = ",
              "SWITCH(TRUE(),Select_Currency=\"USD\",SUM('EdmSales vbSalesAndProfit'[CM1 Amount USD]),",
              "SWITCH(TRUE(),Select_Currency=\"EUR\",SUM('EdmSales vbSalesAndProfit'[CM1 Amount EUR])))",
              "Return CM1/[Units Multiplier]"
            ],
            "lineageTag": "08f12811-301f-4d51-b799-b8410754187c"
          },
          {
            "name": "SAVPM",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "VAR Select_Currency = SELECTEDVALUE('Currency'[Currency])",
              "VAR CM1 = ",
              "SWITCH(TRUE(),Select_Currency=\"USD\",SUM('EdmSales vbSalesAndProfit'[SAVPM Amount USD]),",
              "SWITCH(TRUE(),Select_Currency=\"EUR\",SUM('EdmSales vbSalesAndProfit'[SAVPM Amount EUR])))",
              "Return CM1/[Units Multiplier]"
            ],
            "formatString": "#,0.00",
            "lineageTag": "d86b8d6c-6bb0-42c2-9498-1bc258d33f2a"
          },
          {
            "name": "Payment Terms",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "VAR Select_Currency = SELECTEDVALUE('Currency'[Currency])",
              "VAR CM1 = ",
              "SWITCH(TRUE(),Select_Currency=\"USD\",SUM('EdmSales vbSalesAndProfit'[Payment Terms USD]),",
              "SWITCH(TRUE(),Select_Currency=\"EUR\",SUM('EdmSales vbSalesAndProfit'[Payment Terms EUR])))",
              "Return CM1/[Units Multiplier]"
            ],
            "lineageTag": "f581ca57-6901-4d89-83a8-8b4a18299a79"
          },
          {
            "name": "Freight",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "VAR Select_Currency = SELECTEDVALUE('Currency'[Currency])",
              "VAR CM1 = ",
              "SWITCH(TRUE(),Select_Currency=\"USD\",SUM('EdmSales vbSalesAndProfit'[Freight Amount USD]),",
              "SWITCH(TRUE(),Select_Currency=\"EUR\",SUM('EdmSales vbSalesAndProfit'[Freight Amount EUR])))",
              "Return CM1/[Units Multiplier]"
            ],
            "lineageTag": "3fa30783-7f95-4832-ad04-b443e7022ef7"
          },
          {
            "name": "Cost of Cnsgn Basis",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "VAR Select_Currency = SELECTEDVALUE('Currency'[Currency])",
              "VAR CM1 = ",
              "SWITCH(TRUE(),Select_Currency=\"USD\",SUM('EdmSales vbSalesAndProfit'[Cost Of Cnsgn Basis USD]),",
              "SWITCH(TRUE(),Select_Currency=\"EUR\",SUM('EdmSales vbSalesAndProfit'[Cost Of Cnsgn Basis EUR])))",
              "Return CM1/[Units Multiplier]"
            ],
            "lineageTag": "b7e1fa65-b72e-4ba7-8bd2-5495346b3086"
          },
          {
            "name": "Adj Net Inv Prc",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "VAR Select_Currency = SELECTEDVALUE('Currency'[Currency])",
              "VAR CM1 = ",
              "SWITCH(TRUE(),Select_Currency=\"USD\",SUM('EdmSales vbSalesAndProfit'[Adj Net Invoice Price USD]),",
              "SWITCH(TRUE(),Select_Currency=\"EUR\",SUM('EdmSales vbSalesAndProfit'[Adj Net Invoice Price EUR])))",
              "Return CM1/[Units Multiplier]"
            ],
            "lineageTag": "e89cf38d-3a66-41d9-945e-30e6dd5fa510"
          },
          {
            "name": "PY CM1",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "CALCULATE([CM1],DATEADD('Date Table'[Date],-1,YEAR))",
            "lineageTag": "dc879f25-0a9a-4571-a654-1194a722a074"
          },
          {
            "name": "PY SAVPM",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "CALCULATE([SAVPM],DATEADD('Date Table'[Date],-1,YEAR))",
            "lineageTag": "2f202f12-eb2e-4b25-b020-606b0576f526"
          },
          {
            "name": "PY - Actual Quantity",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "CALCULATE([Actual Quantity],DATEADD('Date Table'[Date],-1,YEAR))",
            "lineageTag": "78f9ee5b-0d1f-43f0-bab4-7967000c5ab4"
          },
          {
            "name": "PY Plan Quantity",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "CALCULATE([Planned Quantity],DATEADD('Date Table'[Date],-1,YEAR))",
            "lineageTag": "d9dce239-303f-48c3-87a3-3b9d5b7a2ba2"
          },
          {
            "name": "CM1 Per Unit Margin",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "DIVIDE([CM1],[Actual Quantity])",
            "formatString": "0.00",
            "lineageTag": "a82bbba6-06a0-41e8-98e0-909d48ade2b5"
          },
          {
            "name": "SAVPM Per Unit Margin",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "DIVIDE([SAVPM],[Actual Quantity])",
            "formatString": "0.00",
            "lineageTag": "d2ec4bee-a67f-4aa7-9e7f-01dd6b8b4968"
          },
          {
            "name": "PY CM1 Per Unit Margin",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "DIVIDE([PY CM1],[PY - Actual Quantity])",
            "formatString": "0.000",
            "lineageTag": "d379c6b6-bf11-4287-b67f-24a0bb00055a"
          },
          {
            "name": "PY SAVPM Per Unit Margin",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "DIVIDE([PY SAVPM],[PY - Actual Quantity])",
            "formatString": "0.000",
            "lineageTag": "e3b2d02a-fe7e-4e22-84a8-df6a8e129482"
          },
          {
            "name": "Adj Net Inv Prc Per Unit",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "DIVIDE([Adj Net Inv Prc],[Actual Quantity])",
            "formatString": "#,0.000",
            "lineageTag": "703f2e4e-cc17-4f00-8c0a-50ab313e7568"
          },
          {
            "name": "PY Adj Net Inv Prc",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "CALCULATE([Adj Net Inv Prc],DATEADD('Date Table'[Date],-1,YEAR))",
            "lineageTag": "1c9c8782-d49e-4509-a8ef-92135728a64a"
          },
          {
            "name": "PY - Adj Net Inv Prc Per Unit",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "DIVIDE([PY Adj Net Inv Prc],[PY - Actual Quantity])",
            "formatString": "0.000",
            "lineageTag": "2d8967be-477f-4ce3-bb3e-fdb700bc1d03"
          },
          {
            "name": "YTD - Actual Quantity",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "VAR YTD_ACTUAL_QTY = TOTALYTD([Actual Quantity],'Date Table'[Date])",
              "RETURN IF([Actual Quantity]=BLANK(),BLANK(),YTD_ACTUAL_QTY)"
            ],
            "lineageTag": "960623dd-cd20-4a0e-a5fd-342ffa5e181d"
          },
          {
            "name": "PY YTD - Actual Quantity",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "TOTALYTD([PY - Actual Quantity],'Date Table'[Date])"
            ],
            "lineageTag": "6f778b66-3d51-4330-b7b6-93d0551cac0f"
          },
          {
            "name": "YTD - Plan Quantity",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "TOTALYTD([Planned Quantity],'Date Table'[Date])"
            ],
            "lineageTag": "205a0899-bfd7-447f-b950-b751b1dd4fc9"
          },
          {
            "name": "YTD - Open Order Quantity",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "TOTALYTD([Open Order Quantity],'Date Table'[Date])"
            ],
            "lineageTag": "a0d4eb6c-3415-4745-9a21-b110848ea053"
          },
          {
            "name": "YTD - Total Quantity",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "(TOTALYTD([Actual Quantity],'Date Table'[Date])+[YTD - Open Order Quantity]+[YTD - Delivered Not Invoice Quantity])"
            ],
            "lineageTag": "1a5c8223-c58b-4c2f-8e9d-a1d6cae3db61"
          },
          {
            "name": "YTD - Delivered Not Invoice Quantity",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "TOTALYTD( [Delivered not Invoiced Quantity],'Date Table'[Date])"
            ],
            "lineageTag": "fcfb7d29-615b-4ea8-ab6f-7fa06c4f427f"
          },
          {
            "name": "YTD CM1",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "TOTALYTD([CM1],'Date Table'[Date])"
            ],
            "lineageTag": "1c5eaad5-c21c-49e8-80b8-619986cdb0c1"
          },
          {
            "name": "PY YTD CM1",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "TOTALYTD(",
              "    [PY CM1],",
              "    'Date Table'[Date])"
            ],
            "lineageTag": "fe1913df-4e41-4501-94e8-22b679e1cf59"
          },
          {
            "name": "YTD SAVPM",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "TOTALYTD([SAVPM],'Date Table'[Date])"
            ],
            "lineageTag": "43200555-2b55-4319-b816-8b036d61bde4"
          },
          {
            "name": "PY YTD SAVPM",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "TOTALYTD(",
              "    [PY SAVPM],",
              "    'Date Table'[Date])"
            ],
            "lineageTag": "56793c11-d6c1-49c5-ab4d-2c520e0691c1"
          },
          {
            "name": "Open Order Volume (+Actual+Open+Delivered Not Invoiced)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "[Actual Quantity]+[Open Order Quantity]+[Delivered not Invoiced Quantity]"
            ],
            "lineageTag": "62052dfa-5690-4681-abbc-bf9636f6267e"
          },
          {
            "name": "Freight Per Unit Margin",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "DIVIDE([Freight],[Actual Quantity])",
            "formatString": "0.00",
            "lineageTag": "3f6bce2f-fd34-47e5-87c2-afd35dda6d75"
          },
          {
            "name": "Variance Actaul Qty vs PY Qty",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "[Actual Quantity]-[PY - Actual Quantity]",
            "lineageTag": "42eda928-eaf3-4997-bfbb-ef9837da9d7b"
          },
          {
            "name": "Variance Actaul Qty vs Plan Qty",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "[Actual Quantity]-[Planned Quantity]",
            "lineageTag": "a3affe88-d2d6-4ea9-a527-b259f32c9240"
          },
          {
            "name": "Top N Rank",
            "expression": [
              "",
              "SWITCH(TRUE(),",
              "[Attributes Order No]=0,[Rank Sold_To Customer],",
              "[Attributes Order No]=1,[Rank Division_name],",
              "[Attributes Order No]=2,[Rank Mkt_segemnt],",
              "[Attributes Order No]=3,[Rank End Use],",
              "[Attributes Order No]=4,[Rank Sold_to sales Rep],",
              "[Attributes Order No]=5,[Rank Prfit center],",
              "[Attributes Order No]=6,[Rank Vendor_name],",
              "[Attributes Order No]=7,[Rank Final_Dest_Country],",
              "[Attributes Order No]=8,[Rank Final_Dest_Region],",
              "[Attributes Order No]=9,[Rank Ship_To Customer],",
              "[Attributes Order No]=10,[Rank Ship_Country],",
              "[Attributes Order No]=11,[Rank Ship_Region],",
              "[Attributes Order No]=12,[Rank Sold_to Country],",
              "[Attributes Order No]=13,[Rank Sold_to Region],",
              "[Attributes Order No]=14,[Rank Product],",
              "[Attributes Order No]=15,[Rank Material])"
            ],
            "formatString": "0",
            "lineageTag": "acaf3a76-ffcc-48ba-b947-6cb9b24b1b82"
          },
          {
            "name": "Attributes Order No",
            "expression": "max(Attributes[Attributes Order])",
            "formatString": "0",
            "lineageTag": "7ab53322-e0da-4f9f-98e5-70572a6b584f"
          },
          {
            "name": "Attributes name",
            "expression": "max(Attributes[Attributes])",
            "lineageTag": "49cd2b0a-e767-481f-a4e9-5eb0dd2983dc"
          },
          {
            "name": "Rank End Use",
            "expression": [
              "var cal = RANKX(ALLSELECTED('EdmMasterData dMarketEndUse'[Mkt End Use Name]),[Sort KPI Measures],,DESC)",
              "Return SWITCH(TRUE(),cal<=[Select Rank Value],cal)"
            ],
            "formatString": "0",
            "lineageTag": "654f3768-f0f2-4222-850f-f0ac088ea2b8"
          },
          {
            "name": "Rank Prfit center",
            "expression": [
              "var cal = RANKX(ALLSELECTED('EdmMasterData dProfitCenter'[Profit Center Name]),[Sort KPI Measures],,DESC)",
              "Return SWITCH(TRUE(),cal<=[Select Rank Value],cal)"
            ],
            "formatString": "0",
            "lineageTag": "30bff507-5e52-4787-84dd-baee84b6e680"
          },
          {
            "name": "Rank Division_name",
            "expression": [
              "",
              "var cal = RANKX(ALLSELECTED('EdmMasterData dDivision'[Division Name]),[Sort KPI Measures],,DESC,Dense)",
              "Return SWITCH(TRUE(),cal<=[Select Rank Value],cal)"
            ],
            "formatString": "0",
            "lineageTag": "b7a3a217-6520-46a1-9c70-de2acfeb4b48"
          },
          {
            "name": "Rank Final_Dest_Country",
            "expression": [
              "",
              "var cal = RANKX(ALLSELECTED('EdmMasterData dCountry'[Final Destination Country]),[Sort KPI Measures],,DESC,Dense)",
              "Return SWITCH(TRUE(),cal<=[Select Rank Value],cal)"
            ],
            "formatString": "0",
            "lineageTag": "d32b3ef0-0486-434f-a081-538654d7ad0e"
          },
          {
            "name": "Rank Mkt_segemnt",
            "expression": [
              "",
              "var cal = RANKX(ALLSELECTED('EdmSales vbSalesAndProfit'[Mkt Seg Name]),[Sort KPI Measures],,DESC,Dense)",
              "Return SWITCH(TRUE(),cal<=[Select Rank Value],cal)"
            ],
            "formatString": "0",
            "lineageTag": "78770b97-0e3a-4af2-b400-abf4e747e94d"
          },
          {
            "name": "Rank Ship_To Customer",
            "expression": [
              "",
              "var cal = RANKX(ALLSELECTED('EdmCustomer dShipToCustomer'[Ship To Customer Name]),[Sort KPI Measures],,DESC,Dense)",
              "Return SWITCH(TRUE(),cal<=[Select Rank Value],cal)"
            ],
            "formatString": "0",
            "lineageTag": "059f9fa5-1b26-4ab4-8623-0f360318466a"
          },
          {
            "name": "Rank Ship_Country",
            "expression": [
              "",
              "var cal = RANKX(ALLSELECTED('EdmCustomer dShipToCustomer'[Ship To Country Name]),[Sort KPI Measures],,DESC,Dense)",
              "Return SWITCH(TRUE(),cal<=[Select Rank Value],cal)"
            ],
            "formatString": "0",
            "lineageTag": "ecd90276-b646-4e19-887c-f7bacaa08f90"
          },
          {
            "name": "Rank Ship_Region",
            "expression": [
              "",
              "var cal = RANKX(ALLSELECTED('EdmCustomer dShipToCustomer'[Ship To Region Name]),[Sort KPI Measures],,DESC,Dense)",
              "Return SWITCH(TRUE(),cal<=[Select Rank Value],cal)"
            ],
            "formatString": "0",
            "lineageTag": "dbee510d-aedf-46ff-b614-e655feeb49d8"
          },
          {
            "name": "Rank Sold_To Customer",
            "expression": [
              "",
              "var cal = RANKX(ALLSELECTED('EdmCustomer dSoldToCustomer'[Sold To Customer Name]),[Sort KPI Measures],,DESC,Dense)",
              "Return SWITCH(TRUE(),cal<=[Select Rank Value],cal)"
            ],
            "formatString": "0",
            "lineageTag": "05b11db5-fa14-47eb-b423-571ef6adea55"
          },
          {
            "name": "Rank Sold_to sales Rep",
            "expression": [
              "",
              "var cal = RANKX(ALLSELECTED('EdmSales vbSalesAndProfit'[SoldTo Sales Rep Name]),[Sort KPI Measures],,DESC,Dense)",
              "Return SWITCH(TRUE(),cal<=[Select Rank Value],cal)"
            ],
            "formatString": "0",
            "lineageTag": "23f56e5f-888f-4f1a-8b4c-ead832bb8c47"
          },
          {
            "name": "Rank Sold_to Country",
            "expression": [
              "",
              "var cal = RANKX(ALLSELECTED('EdmCustomer dSoldToCustomer'[Sold To Country Name]),[Sort KPI Measures],,DESC,Dense)",
              "Return SWITCH(TRUE(),cal<=[Select Rank Value],cal)"
            ],
            "formatString": "0",
            "lineageTag": "2368b2b9-d544-4edd-91b7-2ece54beb650"
          },
          {
            "name": "Rank Sold_to Region",
            "expression": [
              "",
              "var cal = RANKX(ALLSELECTED('EdmCustomer dSoldToCustomer'[Sold To Region Name]),[Sort KPI Measures],,DESC,Dense)",
              "Return SWITCH(TRUE(),cal<=[Select Rank Value],cal)"
            ],
            "formatString": "0",
            "lineageTag": "9913e3c3-8512-4b3d-9b5c-df507fd591c4"
          },
          {
            "name": "Rank Vendor_name",
            "expression": [
              "",
              "var cal = RANKX(ALLSELECTED('EdmVendor dVendor'[Vendor Name]),[Sort KPI Measures],,DESC,Dense)",
              "Return SWITCH(TRUE(),cal<=[Select Rank Value],cal)"
            ],
            "formatString": "0",
            "lineageTag": "4b7fc8cf-bc64-4204-995f-a467856583de"
          },
          {
            "name": "Unit & UOM",
            "expression": "CONCATENATE(max('Units Conversion'[Unit Suffix])&\" \", MAX('EdmMasterData dConversion'[To UoM]))",
            "lineageTag": "7c81aac1-9c3a-425f-89cd-b65427bff020"
          },
          {
            "name": "Currency & UOM",
            "expression": "CONCATENATE(max('Currency'[Currency Symbol])&\"/\", MAX('EdmMasterData dConversion'[To UoM]))",
            "lineageTag": "ae22b33e-3425-4d4b-b612-08cecf779042"
          },
          {
            "name": "Profitability",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "var Profitability_selected = max('Profitability Matrix'[Profitability Matrix Order])",
              "Return if(Profitability_selected=0,[CM1],[SAVPM])"
            ],
            "formatString": "#,0.00",
            "lineageTag": "f6cc7927-fe0c-4e8a-97c3-e89ad0ba36d7"
          },
          {
            "name": "Curr Profitability Matrix",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "VAR Selected_kpi = SELECTEDVALUE('Profitability Matrix'[Profitability Matrix Order])",
              "Return SWITCH(TRUE(),",
              "     Selected_kpi =0, [CM1],",
              "     Selected_kpi = 1, [SAVPM],0",
              ")"
            ],
            "lineageTag": "a599135b-6e67-4c4d-8464-00cc8de1d78d"
          },
          {
            "name": "Top N title",
            "expression": "CONCATENATE(\"Top \",CONCATENATE([Select Rank Value]&\" \",CONCATENATE(VALUES(Attributes[Attributes])&\" by \",VALUES('Sort Matrix Table'[Sort By]))))&\" (YTD) \"",
            "lineageTag": "2c716026-f85a-40ee-9c13-55eec8edcf4a"
          },
          {
            "name": "Unit Margin",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "var Unit_selected = max('CM1/SAVPM Margin Per Unit'[CM1/SAVPM Margin Per Unit Order])",
              "Return if(Unit_selected =0,[CM1 Per Unit Margin],[SAVPM Per Unit Margin])"
            ],
            "formatString": "#,0.000",
            "lineageTag": "1ad3df8a-e9fd-4013-b018-8b35de504e5a"
          },
          {
            "name": "Refreshed at:",
            "expression": "VALUES('Last Refreshed Date Time'[LastRefresh])",
            "formatString": "General Date",
            "lineageTag": "4dfe269a-cce8-4511-a03c-4a4ad6bf1b66"
          },
          {
            "name": "Select KPI Measures",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "var Select_kpi = VALUES('Select KPI Measures'[Select KPI Measures Order])",
              "Return SWITCH(TRUE(),Select_kpi=0,[Actual Quantity],",
              "                     Select_kpi = 1,[CM1],",
              "                     Select_kpi = 2,[CM1 Per Unit Margin],",
              "                     Select_kpi = 3,[SAVPM],",
              "                     Select_kpi = 4,[SAVPM Per Unit Margin],",
              "                     Select_kpi = 5,[Freight Per Unit Margin],0)"
            ],
            "lineageTag": "41ef7718-8aaa-462f-8473-dd7a1c3a03d0"
          },
          {
            "name": "Date Hierarchy level",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "SWITCH(",
              "       TRUE(),",
              "       ISFILTERED('Date Table'[Date].[Day]),",
              "       MAX('Date Table'[Date].[Day]),",
              "       ISFILTERED('Date Table'[Date].[Month]),",
              "       MAX('Date Table'[Year Month]),",
              "       ISFILTERED('Date Table'[Date].[Quarter]),",
              "       max('Date Table'[Year Qtr]),",
              "       ISFILTERED('Date Table'[Date].[Year]),",
              "       max('Date Table'[Date].[Year])",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "368d0ccd-f8b8-42fd-a7b7-27b9d74316e1"
          },
          {
            "name": "PY",
            "expression": "MAX('Date Table'[Prior Year])",
            "formatString": "0",
            "lineageTag": "734203b3-a156-43ec-b949-16e0914aa54c"
          },
          {
            "name": "CY",
            "expression": "MAX('Date Table'[Year])",
            "formatString": "0",
            "lineageTag": "b4ddfff9-c47f-4951-9353-5ec8cef00afa"
          },
          {
            "name": "Sort KPI Measures",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "var Select_kpi = VALUES('Sort Matrix Table'[Sort No.])",
              "Return SWITCH(TRUE(),Select_kpi=0,[CM1],",
              "                     Select_kpi = 1,[SAVPM],",
              "                     Select_kpi = 2,[Actual Quantity],",
              "                     Select_kpi = 3,[CM1 Per Unit Margin],",
              "                     Select_kpi = 4,[SAVPM Per Unit Margin],",
              "                     Select_kpi = 5,[Variance Actaul Qty vs PY Qty],",
              "                     Select_kpi = 6,[Variance Actaul Qty vs Plan Qty],0)"
            ],
            "lineageTag": "23647e64-c1e8-4d65-b023-a56ade7d1d78"
          },
          {
            "name": "PY Profitability",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "var Profitability_selected = max('Profitability Matrix'[Profitability Matrix Order])",
              "Return if(Profitability_selected=0,[PY CM1],[PY SAVPM])"
            ],
            "lineageTag": "6f23b7cd-840d-4ded-af35-fc8bf6c40cf7"
          },
          {
            "name": "PY Unit Margin",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "var Unit_selected = max('CM1/SAVPM Margin Per Unit'[CM1/SAVPM Margin Per Unit Order])",
              "Return if(Unit_selected =0,[PY CM1 Per Unit Margin],[PY SAVPM Per Unit Margin])"
            ],
            "formatString": "0.000",
            "lineageTag": "6a3ff3d6-86e0-4d3c-80dd-81abe29f50a0"
          },
          {
            "name": "YTD Profitability",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "var Profitability_selected = max('Profitability Matrix'[Profitability Matrix Order])",
              "Return if(Profitability_selected=0,[YTD CM1],[YTD SAVPM])"
            ],
            "lineageTag": "6c7a6186-903b-4538-bc4b-7330c100e6a1"
          },
          {
            "name": "PY YTD Profitability",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "var Profitability_selected = max('Profitability Matrix'[Profitability Matrix Order])",
              "Return if(Profitability_selected=0,[PY YTD CM1],[PY YTD SAVPM])"
            ],
            "lineageTag": "2178c9b8-9d85-407b-abbf-19bbf65f1792"
          },
          {
            "name": "Month name",
            "expression": "MAX('Date Table'[Month Name])",
            "lineageTag": "c5fe882c-64da-4644-bd50-1d207dba7065"
          },
          {
            "name": "Coloring Actaul vs Plan Qty",
            "expression": [
              "",
              "var cal =[Actual Quantity]-[Planned Quantity]",
              "Return SWITCH(TRUE(),",
              "[Planned Quantity]=BLANK(),1,",
              "cal<0,2,3)"
            ],
            "formatString": "0",
            "lineageTag": "74aec952-bf19-4b9a-a23d-aa63687a6f11"
          },
          {
            "name": "Coloring Actaul vs PY Qty",
            "expression": [
              "",
              "var cal =[Actual Quantity]-[PY - Actual Quantity]",
              "Return ",
              "SWITCH(TRUE(),",
              "[PY - Actual Quantity]=BLANK(),1,",
              "cal<0,2,3)"
            ],
            "formatString": "0",
            "lineageTag": "d3758d5c-411d-48ab-8061-dbfb5cb83f27"
          },
          {
            "name": "Rank Final_Dest_Region",
            "expression": [
              "",
              "var cal = RANKX(ALLSELECTED('EdmMasterData dCountry'[Final Destination Region]),[Sort KPI Measures],,DESC,Dense)",
              "Return SWITCH(TRUE(),cal<=[Select Rank Value],cal)"
            ],
            "formatString": "0",
            "lineageTag": "23e00201-b718-4fd9-b7cb-33d6dc72cf3c"
          },
          {
            "name": "Row Count",
            "expression": "COUNTROWS('EdmSales vbSalesAndProfit')",
            "formatString": "0",
            "lineageTag": "97707e34-62e6-482c-b350-7fb17e0b9b9e"
          },
          {
            "name": "Attributes Values",
            "expression": [
              "",
              "SWITCH(TRUE(),",
              "[Attributes Order No]=0,MAX('EdmCustomer dSoldToCustomer'[Sold To Customer Name]),",
              "[Attributes Order No]=1,MAX('EdmMasterData dDivision'[Division Name]),",
              "[Attributes Order No]=2,MAX('EdmSales vbSalesAndProfit'[Mkt Seg Name]),",
              "[Attributes Order No]=3,MAX('EdmMasterData dMarketEndUse'[Mkt End Use Name]),",
              "[Attributes Order No]=4,MAX('EdmSales vbSalesAndProfit'[SoldTo Sales Rep Name]),",
              "[Attributes Order No]=5,MAX('Profit name'[Profit Name]),",
              "[Attributes Order No]=6,MAX('EdmVendor dVendor'[Vendor Name]),",
              "[Attributes Order No]=7,MAX('EdmMasterData dCountry'[Final Destination Country]),",
              "[Attributes Order No]=8,MAX('EdmMasterData dCountry'[Final Destination Region]),",
              "[Attributes Order No]=9,MAX('EdmCustomer dShipToCustomer'[Ship To Customer Name]),",
              "[Attributes Order No]=10,MAX('EdmCustomer dShipToCustomer'[Ship To Country Name]),",
              "[Attributes Order No]=11,MAX('EdmCustomer dShipToCustomer'[Ship To Region Name]),",
              "[Attributes Order No]=12,MAX('EdmCustomer dSoldToCustomer'[Sold To Country Name]),",
              "[Attributes Order No]=13,MAX('EdmCustomer dSoldToCustomer'[Sold To Region Name]),",
              "[Attributes Order No]=14,MAX('EdmMaterial dMaterial'[Prod Hierarchy Name]),",
              "[Attributes Order No]=15,MAX('EdmMaterial dMaterial'[Material Name]),BLANK())",
              ""
            ],
            "lineageTag": "47a6aab6-9ebd-4122-afc4-9529c492c6a9"
          },
          {
            "name": "List of Transport Mode Name values",
            "expression": [
              "",
              "VAR __DISTINCT_VALUES_COUNT = DISTINCTCOUNT('EdmMasterData dTransportMode'[Transport Mode Name])",
              "VAR __MAX_VALUES_TO_SHOW = 5",
              "Var Result =",
              "\tIF(",
              "\t\t__DISTINCT_VALUES_COUNT > __MAX_VALUES_TO_SHOW,",
              "\t\tCONCATENATE(",
              "\t\t\tCONCATENATEX(",
              "\t\t\t\tTOPN(",
              "\t\t\t\t\t__MAX_VALUES_TO_SHOW,",
              "\t\t\t\t\tVALUES('EdmMasterData dTransportMode'[Transport Mode Name]),",
              "\t\t\t\t\t'EdmMasterData dTransportMode'[Transport Mode Name],",
              "\t\t\t\t\tASC",
              "\t\t\t\t),",
              "\t\t\t\t'EdmMasterData dTransportMode'[Transport Mode Name],",
              "\t\t\t\t\", \",",
              "\t\t\t\t'EdmMasterData dTransportMode'[Transport Mode Name],",
              "\t\t\t\tASC",
              "\t\t\t),",
              "\t\t\t\", etc.\"",
              "\t\t),",
              "\t\tCONCATENATEX(",
              "\t\t\tVALUES('EdmMasterData dTransportMode'[Transport Mode Name]),",
              "\t\t\t'EdmMasterData dTransportMode'[Transport Mode Name],",
              "\t\t\t\", \",",
              "\t\t\t'EdmMasterData dTransportMode'[Transport Mode Name],",
              "\t\t\tASC",
              "\t\t)",
              "\t)",
              "\tReturn if(ISFILTERED('EdmMasterData dTransportMode'[Transport Mode Name]),Result,\"All\")"
            ],
            "extendedProperties": [
              {
                "name": "MeasureTemplate",
                "type": "json",
                "value": {
                  "daxTemplateName": "ConcatenateValues",
                  "version": 0
                }
              }
            ],
            "lineageTag": "ac33a2a5-c393-430b-b959-b2917bdf995d"
          },
          {
            "name": "Top N CM1",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "IF(ISBLANK([Top N Rank]),BLANK(),[CM1])",
            "lineageTag": "bee4f431-97fb-447d-a169-04788945ba21"
          },
          {
            "name": "Top N CM1 (PY)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "IF(ISBLANK([Top N Rank]),BLANK(),[PY CM1])",
            "lineageTag": "0c195c87-a3ad-43ff-9de1-38a2dad9dac2"
          },
          {
            "name": "Top N SAVPM",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "IF(ISBLANK([Top N Rank]),BLANK(),[SAVPM])",
            "lineageTag": "f44c2107-8ce1-4fd8-a9db-44cb0d4e9cd1"
          },
          {
            "name": "Top N SAVPM (PY)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "IF(ISBLANK([Top N Rank]),BLANK(),[PY SAVPM])",
            "lineageTag": "02da0d53-ff7e-412a-8d69-2a0d70291a9b"
          },
          {
            "name": "Top N Actual Qty",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "IF(ISBLANK([Top N Rank]),BLANK(),[Actual Quantity])",
            "lineageTag": "4e022ebe-8b2c-4d42-8895-9e01fbb9e961"
          },
          {
            "name": "Top N Actual Qty (PY)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "IF(ISBLANK([Top N Rank]),BLANK(),[PY - Actual Quantity])",
            "lineageTag": "c5c3bb90-132b-4b21-b4f6-b43de637d8d2"
          },
          {
            "name": "Top N Planned Qty",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "IF(ISBLANK([Top N Rank]),BLANK(),[Planned Quantity])",
            "lineageTag": "e24a69a4-5f9e-4bfd-9494-204c26969486"
          },
          {
            "name": "Top N Variance Actual Qty vs PY Actual Qty",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "IF(ISBLANK([Top N Rank]),BLANK(),[Variance Actaul Qty vs PY Qty])",
            "lineageTag": "ee50feba-ab39-4ef7-ba1d-76aef04e40df"
          },
          {
            "name": "Top N Variance Actual Qty vs Planned Qty",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "IF(ISBLANK([Top N Rank]),BLANK(),[Variance Actaul Qty vs Plan Qty])",
            "lineageTag": "7bb7d84c-5d04-43ca-a614-ec273d016fcb"
          },
          {
            "name": "Top N CM1/Unit",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "IF(ISBLANK([Top N Rank]),BLANK(),[CM1 Per Unit Margin])",
            "lineageTag": "d8ec2c9c-92d3-4d77-a1db-55e5b62efd6b"
          },
          {
            "name": "Top N CM1/Unit (PY)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "IF(ISBLANK([Top N Rank]),BLANK(),[PY CM1 Per Unit Margin])",
            "lineageTag": "cd8cd672-a651-4616-a30d-c3ffe63017ec"
          },
          {
            "name": "Top N SAVPM/Unit",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "IF(ISBLANK([Top N Rank]),BLANK(),[SAVPM Per Unit Margin])",
            "lineageTag": "864cd80d-9b85-4102-b03e-8daff7e05ac1"
          },
          {
            "name": "Top N SAVPM/Unit (PY)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "IF(ISBLANK([Top N Rank]),BLANK(),[PY SAVPM Per Unit Margin])",
            "lineageTag": "a0acd5dd-fbcd-4b01-9031-30c0838745e4"
          },
          {
            "name": "Top N Adj Net Inv Prc Per Unit",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "IF(ISBLANK([Top N Rank]),BLANK(),[Adj Net Inv Prc Per Unit])",
            "lineageTag": "a5699ed9-83d0-44fc-9ee8-e4897b2cac55"
          },
          {
            "name": "Top N PY - Adj Net Inv Prc Per Unit",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "IF(ISBLANK([Top N Rank]),BLANK(),[PY - Adj Net Inv Prc Per Unit])",
            "lineageTag": "fed99e8a-fc57-4e74-b238-d7656f0476a2"
          },
          {
            "name": "Top N Sort KPI Measures",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "IF(ISBLANK([Top N Rank]),BLANK(),[Sort KPI Measures])",
            "lineageTag": "2c010769-f3eb-4937-9154-3b47ff8eedcf"
          },
          {
            "name": "CM1 with currency",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "",
              "VAR Select_Currency = IF(SELECTEDVALUE('Currency'[Currency],\"USD\") = \"USD\",",
              "SUM('EdmSales vbSalesAndProfit'[CM1 Amount USD]),",
              "SUM('EdmSales vbSalesAndProfit'[CM1 Amount EUR]))",
              "Return Select_Currency/[Units Multiplier]"
            ],
            "formatStringDefinition": {
              "expression": [
                "SELECTEDVALUE('Currency'[Currency Format],",
                "\"\\$#,0.00;(\\$#,0.00);\\$#,0.00\"",
                ")"
              ]
            },
            "isHidden": true,
            "lineageTag": "83d45082-639f-4950-9475-4059cd2f1f15"
          },
          {
            "name": "Max Number",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "VAR MaxValue =",
              "MAXX(",
              "    ALLSELECTED('Date Table'),",
              "    [Current Year Invoiced]+[Current Year Open]",
              ")",
              "VAR MaxPlanned =",
              "MAXX(",
              "    ALLSELECTED('Date Table'),",
              "    [Planned Quantity]",
              ")",
              "Return",
              "Max(MaxValue,MaxPlanned)"
            ],
            "lineageTag": "baae4932-0a2b-4c87-b839-3f643d9bf09c"
          },
          {
            "name": "Rank Product",
            "expression": [
              "var cal = RANKX(ALLSELECTED('EdmMaterial dMaterial'[Prod Hierarchy Name]),[Sort KPI Measures],,DESC)",
              "Return SWITCH(TRUE(),cal<=[Select Rank Value],cal)"
            ],
            "formatString": "0",
            "lineageTag": "bea78e81-fc71-4d59-b270-0e692de9f824"
          },
          {
            "name": "Rank Material",
            "expression": [
              "var cal = RANKX(ALLSELECTED('EdmMaterial dMaterial'[Material Name]),[Sort KPI Measures],,DESC)",
              "Return SWITCH(TRUE(),cal<=[Select Rank Value],cal)"
            ],
            "formatString": "0",
            "lineageTag": "6242cb4a-49af-4790-ba19-2e4dcfa1ca04"
          },
          {
            "name": "TransparentBackground",
            "expression": "If(ISBLANK([Actual Quantity]),\"White\",\"#FFFFFF00\")",
            "lineageTag": "1841506f-8638-48a5-bdd4-87835e15af2c"
          },
          {
            "name": "TransparentFont",
            "expression": "If(ISBLANK([Actual Quantity]),\"Red\",\"#FFFFFF00\")",
            "lineageTag": "a2317cdf-08c6-4e5c-b232-67bdfe34f04b"
          }
        ],
        "partitions": [
          {
            "name": "Measures Table-758f48bc-7311-49e4-988b-4d227691278d",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Currency",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Currency",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "04f936b4-2794-4402-a4de-0f26c855a72e",
            "sourceColumn": "Currency",
            "summarizeBy": "none"
          },
          {
            "name": "Currency Symbol",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "69dc00c3-1a9e-4051-8305-8b9d9255fe27",
            "sourceColumn": "Currency Symbol",
            "summarizeBy": "none"
          },
          {
            "name": "Sort No",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a093c0a7-9a46-4c29-a4e6-447cb28ba833",
            "sourceColumn": "Sort No",
            "summarizeBy": "none"
          },
          {
            "name": "Currency Format",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d8927b02-787e-43a7-8bd4-152b076b8ee7",
            "sourceColumn": "Currency Format",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "1ac99a24-1287-43c1-a27f-26406bf63a48",
        "partitions": [
          {
            "name": "Currency-b30d90f8-93cf-424e-adc8-f6ebc50e061d",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WCg12UdJRUgFiQyCOiVFR1jHQMzCw1oAzNa3hTKVYnWgl19AgoMpHTWuApBFID4gdA9SqAFRkrYvKReEpxcYCAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Currency = _t, #\"Currency Symbol\" = _t, #\"Sort No\" = _t, #\"Currency Format\" = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Currency\", type text}, {\"Currency Symbol\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Profitability Matrix",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "9e7003c26a9e4fa19f8062d1e79a7a78"
          }
        ],
        "columns": [
          {
            "name": "Profitability Matrix",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "094a413f-6a36-4899-b976-e14dffc22329",
            "relatedColumnDetails": {
              "groupByColumns": [
                {
                  "groupingColumn": "Profitability Matrix Fields"
                }
              ]
            },
            "sortByColumn": "Profitability Matrix Order",
            "sourceColumn": "[Value1]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Profitability Matrix Fields",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "extendedProperties": [
              {
                "name": "ParameterMetadata",
                "type": "json",
                "value": {
                  "kind": 2,
                  "version": 3
                }
              }
            ],
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "92bb8ea8-b467-4981-aca9-253df5bac287",
            "sortByColumn": "Profitability Matrix Order",
            "sourceColumn": "[Value2]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Profitability Matrix Order",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "b7889134-e800-4881-af80-15f81802602c",
            "sourceColumn": "[Value3]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "65747b5f-449d-46b8-8c5c-11bad0d2544d",
        "partitions": [
          {
            "name": "Profitability Matrix-4b5da86c-5845-4328-9383-3d29975d863c",
            "mode": "import",
            "source": {
              "expression": [
                "{",
                "    (\"CM1\", NAMEOF('Measures Table'[CM1]), 0),",
                "    (\"SAVPM\", NAMEOF('Measures Table'[SAVPM]), 1)",
                "}"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Profitability Matrix - YTD",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "8ef4770deb234ff6a943cea00f6187ac"
          }
        ],
        "columns": [
          {
            "name": "Profitability Matrix - Running",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "23189cbd-da8c-4595-bf6b-0bb3a336faed",
            "relatedColumnDetails": {
              "groupByColumns": [
                {
                  "groupingColumn": "Profitability Matrix - Running Fields"
                }
              ]
            },
            "sortByColumn": "Profitability Matrix - Running Order",
            "sourceColumn": "[Value1]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Profitability Matrix - Running Fields",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "extendedProperties": [
              {
                "name": "ParameterMetadata",
                "type": "json",
                "value": {
                  "kind": 2,
                  "version": 3
                }
              }
            ],
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "a6c2e136-f78b-4cd4-a006-6bda17f37965",
            "sortByColumn": "Profitability Matrix - Running Order",
            "sourceColumn": "[Value2]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Profitability Matrix - Running Order",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "9d0ba1fd-d4e7-4057-a6ab-441de0200f7e",
            "sourceColumn": "[Value3]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "86a15e2c-9477-4760-b318-cb1ab1a707f7",
        "partitions": [
          {
            "name": "Profitability Matrix - YTD-dbaec4d1-a056-40a5-a55f-c8417e800761",
            "mode": "import",
            "source": {
              "expression": [
                "{",
                "    (\"YTD - CM1\", NAMEOF('Measures Table'[YTD CM1]), 0),",
                "    (\"YTD - SAVPM\", NAMEOF('Measures Table'[YTD SAVPM]), 1)",
                "}"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Profitability Matrix - PY YTD",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "88c1cff926d542bda2adfe3ee005e2df"
          }
        ],
        "columns": [
          {
            "name": "Profitability Matrix - Running PY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "6e4d5c88-6b0f-429b-bbb5-a7de694955ea",
            "relatedColumnDetails": {
              "groupByColumns": [
                {
                  "groupingColumn": "Profitability Matrix - Running PY Fields"
                }
              ]
            },
            "sortByColumn": "Profitability Matrix - Running PY Order",
            "sourceColumn": "[Value1]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Profitability Matrix - Running PY Fields",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "extendedProperties": [
              {
                "name": "ParameterMetadata",
                "type": "json",
                "value": {
                  "kind": 2,
                  "version": 3
                }
              }
            ],
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "20908a11-7701-4ad8-923a-32275024689a",
            "sortByColumn": "Profitability Matrix - Running PY Order",
            "sourceColumn": "[Value2]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Profitability Matrix - Running PY Order",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "27069795-796b-4b3b-868c-c231fee41b32",
            "sourceColumn": "[Value3]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "a829d7bd-7076-47a8-ba57-612ed59319e8",
        "partitions": [
          {
            "name": "Profitability Matrix - PY YTD-2820ba34-5011-47ce-ae5f-9e593e89fa76",
            "mode": "import",
            "source": {
              "expression": [
                "{",
                "    (\"PY YTD - CM1\", NAMEOF('Measures Table'[PY YTD CM1]), 0),",
                "    (\"PY YTD - SAVPM\", NAMEOF('Measures Table'[PY YTD SAVPM]), 1)",
                "}"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Profitability Matrix - PY",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "7b98f101450d4757bb50e5f0fff476bb"
          }
        ],
        "columns": [
          {
            "name": "Profitability Matrix - PY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "c88b1b65-3cca-4e74-a453-bf814727cab9",
            "relatedColumnDetails": {
              "groupByColumns": [
                {
                  "groupingColumn": "Profitability Matrix - PY Fields"
                }
              ]
            },
            "sortByColumn": "Profitability Matrix - PY Order",
            "sourceColumn": "[Value1]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Profitability Matrix - PY Fields",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "extendedProperties": [
              {
                "name": "ParameterMetadata",
                "type": "json",
                "value": {
                  "kind": 2,
                  "version": 3
                }
              }
            ],
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "9609c5bb-550d-4ba7-9984-64bb573d31bf",
            "sortByColumn": "Profitability Matrix - PY Order",
            "sourceColumn": "[Value2]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Profitability Matrix - PY Order",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "b1d85037-c8e0-44bb-ab40-7df414e26bd2",
            "sourceColumn": "[Value3]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "d50f61c7-802d-435c-a7a3-a0150010b762",
        "partitions": [
          {
            "name": "Profitability Matrix - PY-3b796745-1376-4221-bab0-8d121fb8e6ba",
            "mode": "import",
            "source": {
              "expression": [
                "{",
                "    (\"PY - CM1\", NAMEOF('Measures Table'[PY CM1]), 0),",
                "    (\"PY - SAVPM\", NAMEOF('Measures Table'[PY SAVPM]), 1)",
                "}"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "CM1/SAVPM Margin Per Unit",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "1aaff558141745f08a475170296ee820"
          }
        ],
        "columns": [
          {
            "name": "CM1/SAVPM Margin Per Unit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "a02a4d11-c96d-4486-8d98-4a0adaf6f11e",
            "relatedColumnDetails": {
              "groupByColumns": [
                {
                  "groupingColumn": "CM1/SAVPM Margin Per Unit Fields"
                }
              ]
            },
            "sortByColumn": "CM1/SAVPM Margin Per Unit Order",
            "sourceColumn": "[Value1]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "CM1/SAVPM Margin Per Unit Fields",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "extendedProperties": [
              {
                "name": "ParameterMetadata",
                "type": "json",
                "value": {
                  "kind": 2,
                  "version": 3
                }
              }
            ],
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "49cc9abe-4093-4d66-b3ed-688353bf9f58",
            "sortByColumn": "CM1/SAVPM Margin Per Unit Order",
            "sourceColumn": "[Value2]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "CM1/SAVPM Margin Per Unit Order",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "7a75ec2c-a46a-42e5-802b-324f935dcf9b",
            "sourceColumn": "[Value3]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "a6800e30-5bea-4390-ae8c-a9a844ad483e",
        "partitions": [
          {
            "name": "CM1/SAVPM Margin Per Unit-40b56e01-748e-422f-859f-9ba6dc4c2172",
            "mode": "import",
            "source": {
              "expression": [
                "{",
                "    (\"CM1 Per Unit Margin\", NAMEOF('Measures Table'[CM1 Per Unit Margin]), 0),",
                "    (\"SAVPM Per Unit Margin\", NAMEOF('Measures Table'[SAVPM Per Unit Margin]), 1)",
                "}"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "PY CM1/SAVPM Margin Per Unit",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "439baaea0afc47919207290f10cb5f15"
          }
        ],
        "columns": [
          {
            "name": "PY CM1/SAVPM Margin Per Unit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "7bfbd403-7873-44e3-8659-8427bdc0ad79",
            "relatedColumnDetails": {
              "groupByColumns": [
                {
                  "groupingColumn": "PY CM1/SAVPM Margin Per Unit Fields"
                }
              ]
            },
            "sortByColumn": "PY CM1/SAVPM Margin Per Unit Order",
            "sourceColumn": "[Value1]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "PY CM1/SAVPM Margin Per Unit Fields",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "extendedProperties": [
              {
                "name": "ParameterMetadata",
                "type": "json",
                "value": {
                  "kind": 2,
                  "version": 3
                }
              }
            ],
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "dbd599cd-057f-46a2-a338-c4c3272e77e5",
            "sortByColumn": "PY CM1/SAVPM Margin Per Unit Order",
            "sourceColumn": "[Value2]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "PY CM1/SAVPM Margin Per Unit Order",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "622ed276-b0d1-4eb5-a824-0ea39b220036",
            "sourceColumn": "[Value3]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "1268e133-c8ae-4b35-9cdb-47d597531f89",
        "partitions": [
          {
            "name": "PY CM1/SAVPM Margin Per Unit-366e7f9d-c584-4a3d-8a8d-b99ff2dbc94a",
            "mode": "import",
            "source": {
              "expression": [
                "{",
                "    (\"PY - CM1 Per Unit Margin\", NAMEOF('Measures Table'[PY CM1 Per Unit Margin]), 0),",
                "    (\"PY - SAVPM Per Unit Margin\", NAMEOF('Measures Table'[PY SAVPM Per Unit Margin]), 1)",
                "}"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Attributes",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "f7bb74228588497c9ce9871bd91158f9"
          }
        ],
        "columns": [
          {
            "name": "Attributes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "e629cdfa-fdbf-4e2c-978d-0100fc97a2a0",
            "relatedColumnDetails": {
              "groupByColumns": [
                {
                  "groupingColumn": "Attributes Fields"
                }
              ]
            },
            "sortByColumn": "Attributes Order",
            "sourceColumn": "[Value1]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Attributes Fields",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "extendedProperties": [
              {
                "name": "ParameterMetadata",
                "type": "json",
                "value": {
                  "kind": 2,
                  "version": 3
                }
              }
            ],
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "de892bd0-459e-4adc-b827-99a89f4e01d1",
            "sortByColumn": "Attributes Order",
            "sourceColumn": "[Value2]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Attributes Order",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "e3a83399-a9e2-4360-a6e8-c7f2c7642df2",
            "sourceColumn": "[Value3]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "3ff64b00-871e-4b20-811b-32ebabf47d83",
        "partitions": [
          {
            "name": "Attributes-2b0e55dc-8511-4c38-b370-7e5422d7a0af",
            "mode": "import",
            "source": {
              "expression": [
                "{",
                "    (\"Sold-to Customer\", NAMEOF('EdmCustomer dSoldToCustomer'[Sold To Customer Name]), 0),",
                "    (\"Division\", NAMEOF('EdmMasterData dDivision'[Division Name]), 1),",
                "    (\"Market Segment\", NAMEOF('EdmSales vbSalesAndProfit'[Mkt Seg Name]), 2),",
                "    (\"End Use\", NAMEOF('EdmMasterData dMarketEndUse'[Mkt End Use Name]), 3),",
                "    (\"Sold-to Sales Rep\", NAMEOF('EdmSales vbSalesAndProfit'[SoldTo Sales Rep Name]), 4),",
                "    (\"Profit Center\", NAMEOF('EdmMasterData dProfitCenter'[Profit Center Name]), 5),",
                "    (\"Vendor\", NAMEOF('EdmVendor dVendor'[Vendor Name]), 6),",
                "    (\"Final Dest Contry\", NAMEOF('EdmMasterData dCountry'[Final Destination Country]), 7),",
                "    (\"Final Dest Region\", NAMEOF('EdmMasterData dCountry'[Final Destination Region]), 8),",
                "    (\"Ship-to Customer\", NAMEOF('EdmCustomer dShipToCustomer'[Ship To Customer Name]), 9),",
                "    (\"Ship-to Country\", NAMEOF('EdmCustomer dShipToCustomer'[Ship To Country Name]),10),",
                "    (\"Ship-to Region\", NAMEOF('EdmCustomer dShipToCustomer'[Ship To Region Name]), 11),",
                "    (\"Sold-to Country\", NAMEOF('EdmCustomer dSoldToCustomer'[Sold To Country Name]), 12),",
                "    (\"Sold-to Region\", NAMEOF('EdmCustomer dSoldToCustomer'[Sold To Region Name]), 13),",
                "    (\"Product\", NAMEOF('EdmMaterial dMaterial'[Prod Hierarchy Name]), 14),",
                "    (\"Material\", NAMEOF('EdmMaterial dMaterial'[Material Name]), 15) ",
                "}"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Sort Matrix Table",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Sort By",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c16dc2ba-58ba-4fde-a8e4-8c532cb19501",
            "sourceColumn": "Sort By",
            "summarizeBy": "none"
          },
          {
            "name": "Sort No.",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "572be781-19df-410b-95d3-dd745bd12f46",
            "sourceColumn": "Sort No.",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "e7a72b79-64ad-4bc6-bc63-e1d37ae2d340",
        "partitions": [
          {
            "name": "Sort Matrix Table-36366a5a-77db-4c78-8f5c-34880ea00fb6",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WcvY1VNJRMlCK1YlWCnYMC/AF8gzBPMfkktLEHIXA0sS8ksySSqC4EVgcqEM/NC+zRME3sSg9Mw8obozQjSZjApYJSyzKTMxLTlWAGVlSqVBWrBAQiSQAVGyKV3FOYh5UnZlSbCwA\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#\"Sort By\" = _t, #\"Sort No.\" = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Sort By\", type text}, {\"Sort No.\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Profit name",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Profit Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d7d83e98-66d3-409f-8783-48295972a20a",
            "sourceColumn": "Profit Name",
            "summarizeBy": "none"
          },
          {
            "name": "Sort no",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "2e33be7a-873a-4e65-87a2-d1544d1f2426",
            "sourceColumn": "Sort no",
            "summarizeBy": "none"
          },
          {
            "name": "Unit Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e2907ca2-2982-44da-a543-5c476ac6a96c",
            "sourceColumn": "Unit Name",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "0fd7884c-58bf-40d4-be51-60c4a6e3ccaf",
        "partitions": [
          {
            "name": "Profit name-7f99ee97-5f5c-430a-9936-bf1b3a1da246",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WcvY1VNJRMgBiIEs/NC+zREEpVidaKdgxLMAXKAqSBbPBckqxsQA=\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#\"Profit Name\" = _t, #\"Sort no\" = _t, #\"Unit Name\" = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Profit Name\", type text}, {\"Sort no\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Select Rank",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "d0881a32a664475d91dda1829b123ac4"
          }
        ],
        "columns": [
          {
            "name": "Select Rank",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "extendedProperties": [
              {
                "name": "ParameterMetadata",
                "type": "json",
                "value": {
                  "version": 0
                }
              }
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "f42b46b1-6910-4603-9c45-011c34b73ba2",
            "sourceColumn": "[Value]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "76d189c0-30dd-43be-a466-eeff3e67d073",
        "measures": [
          {
            "name": "Select Rank Value",
            "expression": "SELECTEDVALUE('Select Rank'[Select Rank])",
            "formatString": "0",
            "lineageTag": "be1b54b5-d488-47b3-ae3b-9b8e8636c293"
          }
        ],
        "partitions": [
          {
            "name": "Select Rank-5bd8239f-6d42-42a5-bac7-4b5eb62d5c96",
            "mode": "import",
            "source": {
              "expression": "GENERATESERIES(1, 200, 1)",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Select KPI Measures",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "9215afce66ea40eabf80eb7300f90c68"
          }
        ],
        "columns": [
          {
            "name": "Select KPI Measures",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "6b635419-dd07-4f58-9332-7fbe17fde7e0",
            "relatedColumnDetails": {
              "groupByColumns": [
                {
                  "groupingColumn": "Select KPI Measures Fields"
                }
              ]
            },
            "sortByColumn": "Select KPI Measures Order",
            "sourceColumn": "[Value1]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Select KPI Measures Fields",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "extendedProperties": [
              {
                "name": "ParameterMetadata",
                "type": "json",
                "value": {
                  "kind": 2,
                  "version": 3
                }
              }
            ],
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "975be5ed-1246-49df-b7db-083155d3a494",
            "sortByColumn": "Select KPI Measures Order",
            "sourceColumn": "[Value2]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Select KPI Measures Order",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "3ecad4fa-0b4e-4ddb-9b02-62aff22ca3cf",
            "sourceColumn": "[Value3]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "827b5482-b8a6-4f2b-a1ad-0141912ed496",
        "partitions": [
          {
            "name": "Select KPI Measures-ecbc459d-46f1-4ff7-8bb2-02abe3baae25",
            "mode": "import",
            "source": {
              "expression": [
                "{",
                "    (\"Actual Quantity\", NAMEOF('Measures Table'[Actual Quantity]), 0),",
                "    (\"CM1\", NAMEOF('Measures Table'[CM1]), 1),",
                "    (\"CM1 Per Unit Margin\", NAMEOF('Measures Table'[CM1 Per Unit Margin]), 2),",
                "    (\"SAVPM\", NAMEOF('Measures Table'[SAVPM]), 3),",
                "    (\"SAVPM Per Unit Margin\", NAMEOF('Measures Table'[SAVPM Per Unit Margin]), 4),",
                "    (\"Freight Per Unit Margin\", NAMEOF('Measures Table'[Freight Per Unit Margin]), 5)",
                "}"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Source Table",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Source",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b2f8cfe9-6e28-432a-bf0c-0d2aae02f35d",
            "sourceColumn": "Source",
            "summarizeBy": "none"
          },
          {
            "name": "Source name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "301cc877-aa4c-4e7d-820f-49a9262a2bcc",
            "sourceColumn": "Source name",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "a72a7527-605b-47f0-ae52-713a24cf6867",
        "partitions": [
          {
            "name": "Source Table-e9f5de15-7cb2-45d7-87c1-293fbfeb6e56",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WyqlM0s1NzMzTKyjKLEssSc3JzMvWK87LL0/LScxOTc7PLSgtycxL1wOylHRIUh0bCwA=\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Source = _t, #\"Source name\" = _t])",
                "in",
                "    Source",
                "",
                "",
                "/*",
                "",
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"lc+xDsIgFIXhd2EuhFiN7awPYNKRMAD30pi0vRawjW8vm5CYGJcz/l+OUmx6WR7Xicc0gnEUkEt5ECfrfe+d7dpWCjDJWBNR7PcFaI9iwcQapgZ6BoeaqyGNeb+WNNPNBwHc/kUuNM+05PwVtwKpSjXyCFAgFuHcGzyi7+zvJ7dAUChVKiv6DQ==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Source = _t, #\"Source name\" = _t]),",
                "    #\"Filtered Rows\" = Table.SelectRows(Source, each [Source] = Server1)",
                "in",
                "    #\"Filtered Rows\"",
                "    ",
                "*/"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "EdmMasterData dDivision",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Division",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "67d4440a-d06c-4c6b-acab-6ceb411333ea",
            "sourceColumn": "Division",
            "summarizeBy": "none"
          },
          {
            "name": "Division Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cb927bad-47bf-48b9-a23c-83c64b862058",
            "sourceColumn": "Division Name",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "ec86b46e-5798-487f-99dc-aeecb92960c2",
        "partitions": [
          {
            "name": "EdmMasterData dDivision-528ade92-e838-424f-b2a9-f477b1622091",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "   Source = Value.NativeQuery(Snowflake.Databases(server,warehouse,[Role=role]){[Name=db]}[Data], \"SELECT DISTINCT \"\"Division\"\", \"\"Division Name\"\" FROM \"&db&\".EDMMASTERDATA.\"\"vdDivision\"\" \", null, [EnableFolding=true])",
                "in",
                "    Source",
                "",
                "/*",
                "let",
                "    Source = Sql.Database(\"lyb-sql-stgdacore-002.5bff9fcb8330.database.windows.net\", \"Source\", [Query=\"SELECT DISTINCT#(lf)[Division],[Division Name]#(lf)FROM EdmMasterData.vdDivision\", MultiSubnetFailover=true])",
                "in",
                "    Source",
                "*/"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "EdmMasterData dMarketEndUse",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Mkt End Use",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "960a36a4-0b43-4b46-b372-eb3406f0c745",
            "sourceColumn": "Mkt End Use",
            "summarizeBy": "none"
          },
          {
            "name": "Mkt End Use Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "57e5b47d-009a-4aee-bdce-caf197ddd933",
            "sourceColumn": "Mkt End Use Name",
            "summarizeBy": "none"
          },
          {
            "name": "Mkt End Use Group",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "142a3985-36e7-4186-a091-c9d4f9691d17",
            "sourceColumn": "Mkt End Use Group",
            "summarizeBy": "none"
          },
          {
            "name": "Mkt End Use Group Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bf9757f2-df00-42e1-a6a3-b17c40bff3e4",
            "sourceColumn": "Mkt End Use Group Name",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "35ce5e46-fdf9-4a89-a625-f920944268e6",
        "partitions": [
          {
            "name": "EdmMasterData dMarketEndUse-4d98a3d6-470e-4cf3-a203-4f74400f2dd6",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "   Source = Value.NativeQuery(Snowflake.Databases(server,warehouse,[Role=role]){[Name=db]}[Data], \"SELECT DISTINCT \"\"Mkt End Use\"\",\"\"Mkt End Use Name\"\",\"\"Mkt End Use Group\"\",\"\"Mkt End Use Group Name\"\" FROM \"&db&\".EDMMASTERDATA.\"\"vdMarketEndUse\"\" \", null, [EnableFolding=true])",
                "in",
                "    Source",
                "",
                "/*",
                "let",
                "    Source = Sql.Database(\"lyb-sql-stgdacore-002.5bff9fcb8330.database.windows.net\", \"Source\", [Query=\"SELECT DISTINCT#(lf)[Mkt End Use],[Mkt End Use Name],[Mkt End Use Group],[Mkt End Use Group Name]#(lf)FROM EdmMasterData.vdMarketEndUse\", MultiSubnetFailover=true])",
                "in",
                "    Source",
                "*/"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "EdmPlant dPlant",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Plant",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "507879f4-1af6-4a4e-b0ad-0530d1d116d0",
            "sourceColumn": "Plant",
            "summarizeBy": "none"
          },
          {
            "name": "Plant Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2481b03e-db64-4b0f-a93b-acbdeed1ab79",
            "sourceColumn": "Plant Name",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "334fde91-8dfe-41cf-a307-809df21fb4ca",
        "partitions": [
          {
            "name": "EdmPlant dPlant-09226688-b752-440e-9d17-4fb97b58683d",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "   Source = Value.NativeQuery(Snowflake.Databases(server,warehouse,[Role=role]){[Name=db]}[Data], \"SELECT DISTINCT \"\"Plant\"\", \"\"Plant Name\"\" FROM \"&db&\".EDMPLANT.\"\"vdPlant\"\" \", null, [EnableFolding=true])",
                "in",
                "    Source",
                "",
                "/*",
                "let",
                "    Source = Sql.Database(\"lyb-sql-stgdacore-002.5bff9fcb8330.database.windows.net\", \"Source\", [Query=\"SELECT DISTINCT#(lf)[Plant],[Plant Name]#(lf)from EdmPlant.vdPlant\", MultiSubnetFailover=true])",
                "in",
                "    Source",
                "*/"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "EdmMasterData dSalesOrganisation",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Sales Org",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "af1a9a1a-3b06-4fdc-b10e-9b2d7e905469",
            "sourceColumn": "Sales Org",
            "summarizeBy": "none"
          },
          {
            "name": "Sales Org Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f68d0bf2-134b-4a19-b075-199302f9c818",
            "sourceColumn": "Sales Org Name",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "65367f14-ba8b-405e-a410-3bc59299fc49",
        "partitions": [
          {
            "name": "EdmMasterData dSalesOrganisation-5aa2d047-0b9c-409b-85ca-c16e8b7998a8",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "   Source = Value.NativeQuery(Snowflake.Databases(server,warehouse,[Role=role]){[Name=db]}[Data], \"SELECT DISTINCT \"\"Sales Org\"\", \"\"Sales Org Name\"\" FROM \"&db&\".EDMMASTERDATA.\"\"vdSalesOrganisation\"\" \", null, [EnableFolding=true])",
                "in",
                "    Source",
                "",
                "/*",
                "let",
                "    Source = Sql.Database(\"lyb-sql-stgdacore-002.5bff9fcb8330.database.windows.net\", \"Source\", [Query=\"SELECT DISTINCT#(lf)[Sales Org],[Sales Org Name]#(lf)FROM EdmMasterData.vdSalesOrganisation\", MultiSubnetFailover=true])",
                "in",
                "    Source",
                "*/"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "EdmMasterData dSalesType",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Sales Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f5d010e0-fcff-4295-ab42-7c05b8d16e6a",
            "sourceColumn": "Sales Type",
            "summarizeBy": "none"
          },
          {
            "name": "Sales Type Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5950dc03-bb1a-4c18-bd01-2e3cc26af3a5",
            "sourceColumn": "Sales Type Name",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "bd876f50-9885-4c31-ad60-daedfb8df0cb",
        "partitions": [
          {
            "name": "EdmMasterData dSalesType-0c3eae8a-4499-46bb-8eff-a80865326bb4",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "",
                "/*",
                "    Source = Sql.Database(\"lyb-sql-stgdacore-002.5bff9fcb8330.database.windows.net\", \"Source\", [MultiSubnetFailover=true]),",
                "    EdmMasterData_vdSalesTypeLoad = Source{[Schema=\"EdmMasterData\",Item=\"vdSalesType\"]}[Data],",
                "*/",
                "    Source = Snowflake.Databases(server,warehouse,[Role=role]),",
                "    DEV_SOURCE_Database = Source{[Name=db,Kind=\"Database\"]}[Data],",
                "    EDMMASTERDATA_Schema = DEV_SOURCE_Database{[Name=\"EDMMASTERDATA\",Kind=\"Schema\"]}[Data],",
                "    EdmMasterData_vdSalesTypeLoad = EDMMASTERDATA_Schema{[Name=\"vdSalesType\",Kind=\"View\"]}[Data],",
                "    #\"Removed Other Columns\" = Table.SelectColumns(EdmMasterData_vdSalesTypeLoad,{\"Sales Type\", \"Sales Type Name\"})",
                "in",
                "    #\"Removed Other Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "EdmMasterData dExportIndicator",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Export Indicator",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c6c825b1-0855-4e74-804e-6223aaf5eeb2",
            "sourceColumn": "Export Indicator",
            "summarizeBy": "none"
          },
          {
            "name": "Export Indicator Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c90a8dfc-9423-4b3f-9620-b8f87dd40c0b",
            "sourceColumn": "Export Indicator Name",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "0d1b15cd-4c93-41e6-8d81-df1f25a394dc",
        "partitions": [
          {
            "name": "EdmMasterData dExportIndicator-c86ab69d-afbd-4c62-bd4e-3ba27e3d3943",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "",
                "/*",
                "    Source = Sql.Database(\"lyb-sql-stgdacore-002.5bff9fcb8330.database.windows.net\", \"Source\", [MultiSubnetFailover=true]),",
                "    EdmMasterData_vdExportIndicatorLoad = Source{[Schema=\"EdmMasterData\",Item=\"vdExportIndicator\"]}[Data],",
                "*/",
                "\tSource = Snowflake.Databases(server,warehouse,[Role=role]),",
                "    DEV_SOURCE_Database = Source{[Name=db,Kind=\"Database\"]}[Data],",
                "    EDMMASTERDATA_Schema = DEV_SOURCE_Database{[Name=\"EDMMASTERDATA\",Kind=\"Schema\"]}[Data],",
                "    EdmMasterData_vdExportIndicatorLoad = EDMMASTERDATA_Schema{[Name=\"vdExportIndicator\",Kind=\"View\"]}[Data],",
                "    #\"Removed Other Columns\" = Table.SelectColumns(EdmMasterData_vdExportIndicatorLoad,{\"Export Indicator\", \"Export Indicator Name\"})",
                "in",
                "    #\"Removed Other Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "EdmMasterData dTransportMode",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Transport Mode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2507b0f8-7a34-4623-9db8-c6ed53653a2e",
            "sourceColumn": "Transport Mode",
            "summarizeBy": "none"
          },
          {
            "name": "Transport Mode Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a4e544ef-11c0-4627-9fb7-6153c24b498f",
            "sourceColumn": "Transport Mode Name",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "67148b72-41b5-4468-ada6-97b2f494e03d",
        "partitions": [
          {
            "name": "EdmMasterData dTransportMode-6350d556-d65c-4573-acf7-70eefbd2449b",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "/*",
                "    Source = Sql.Database(\"lyb-sql-stgdacore-002.5bff9fcb8330.database.windows.net\", \"Source\", [MultiSubnetFailover=true]),",
                "    EdmMasterData_vdTransportModeLoad = Source{[Schema=\"EdmMasterData\",Item=\"vdTransportMode\"]}[Data],",
                "*/",
                "\tSource = Snowflake.Databases(server,warehouse,[Role=role]),",
                "    DEV_SOURCE_Database = Source{[Name=db,Kind=\"Database\"]}[Data],",
                "    EDMMASTERDATA_Schema = DEV_SOURCE_Database{[Name=\"EDMMASTERDATA\",Kind=\"Schema\"]}[Data],",
                "    EdmMasterData_vdTransportModeLoad = EDMMASTERDATA_Schema{[Name=\"vdTransportMode\",Kind=\"View\"]}[Data],",
                "    #\"Removed Other Columns\" = Table.SelectColumns(EdmMasterData_vdTransportModeLoad,{\"Transport Mode\", \"Transport Mode Name\"})",
                "in",
                "    #\"Removed Other Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "EdmCompany dCompany",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Company",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "315a632c-60e9-42fd-9327-c293df3b0017",
            "sourceColumn": "Company",
            "summarizeBy": "none"
          },
          {
            "name": "Company Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e6a58897-b790-464a-bc7a-ab0d31670c5a",
            "sourceColumn": "Company Name",
            "summarizeBy": "none"
          },
          {
            "name": "Company Country",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "92368cf5-d5d8-4790-ab90-d5a472237d93",
            "sourceColumn": "Company Country",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "176714de-1944-4843-a0e6-59a4a0d7f89e",
        "partitions": [
          {
            "name": "EdmCompany dCompany-4d35e6ef-787e-45e7-9ab3-e39b2c36486e",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Value.NativeQuery(Snowflake.Databases(server,warehouse,[Role=role]){[Name=db]}[Data], \"SELECT DISTINCT \"\"Company\"\",\"\"Company Name\"\",\"\"Country Name\"\" as \"\"Company Country\"\" FROM \"&db&\".EDMCOMPANY.\"\"vdCompany\"\" \", null, [EnableFolding=true])",
                "in",
                "    Source",
                "",
                "/*",
                "let",
                "    Source = Sql.Database(\"lyb-sql-stgdacore-002.5bff9fcb8330.database.windows.net\", \"Source\", [Query=\"SELECT DISTINCT#(lf)[Company],[Company Name],[Country Name] as [Company Country]#(lf)FROM EdmCompany.vdCompany\", MultiSubnetFailover=true])",
                "in",
                "    Source",
                "*/"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "EdmMasterData dProfitCenter",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Profit Center",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2ed738d9-fe5a-4201-bbcc-a56c0b2c0889",
            "sourceColumn": "Profit Center",
            "summarizeBy": "none"
          },
          {
            "name": "Profit Center Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b3668fd2-6d86-4322-ae4a-d87cd92bf831",
            "sourceColumn": "Profit Center Name",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "2711f126-d109-4ab3-8f6f-357824db21ac",
        "partitions": [
          {
            "name": "EdmMasterData dProfitCenter-bf3f31bb-d4e7-45c0-80fc-b7553b701987",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Value.NativeQuery(Snowflake.Databases(server,warehouse,[Role=role]){[Name=db]}[Data], \"SELECT DISTINCT \"\"Profit Center\"\",\"\"Profit Center Name\"\" FROM \"&db&\".EDMMASTERDATA.\"\"vdProfitCenter\"\" \", null, [EnableFolding=true])",
                "in",
                "    Source",
                "",
                "",
                "/*",
                "let",
                "    Source = Sql.Database(\"lyb-sql-stgdacore-002.5bff9fcb8330.database.windows.net\", \"Source\", [Query=\"SELECT DISTINCT#(lf)[Profit Center],[Profit Center Name]#(lf)FROM EdmMasterData.vdProfitCenter\", MultiSubnetFailover=true])",
                "in",
                "    Source",
                "*/"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "EdmMasterData dBusinessUnit",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "BU",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4425f19c-e807-45fc-beb9-70d15ca1017e",
            "sourceColumn": "BU",
            "summarizeBy": "none"
          },
          {
            "name": "BU Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4658ffb1-a8c6-424d-b4eb-f1c722b941bb",
            "sourceColumn": "BU Name",
            "summarizeBy": "none"
          },
          {
            "name": "BU Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "00208728-b567-4dac-aa93-1df960bbf3b5",
            "sourceColumn": "BU Type",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "f4bcc681-4173-4008-a92e-ac4929edcedb",
        "partitions": [
          {
            "name": "EdmMasterData dBusinessUnit-ed14a88b-9997-4c68-8eff-0a0845f5168f",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "",
                "/*",
                "    Source = Sql.Database(\"lyb-sql-stgdacore-002.5bff9fcb8330.database.windows.net\", \"Source\", [MultiSubnetFailover=true]),",
                "    EdmMasterData_vdBusinessUnitLoad = Source{[Schema=\"EdmMasterData\",Item=\"vdBusinessUnit\"]}[Data],",
                "*/",
                "\tSource = Snowflake.Databases(server,warehouse,[Role=role]),",
                "    DEV_SOURCE_Database = Source{[Name=db,Kind=\"Database\"]}[Data],",
                "    EDMMASTERDATA_Schema = DEV_SOURCE_Database{[Name=\"EDMMASTERDATA\",Kind=\"Schema\"]}[Data],",
                "    EdmMasterData_vdBusinessUnitLoad = EDMMASTERDATA_Schema{[Name=\"vdBusinessUnit\",Kind=\"View\"]}[Data],",
                "    #\"Removed Other Columns\" = Table.SelectColumns(EdmMasterData_vdBusinessUnitLoad,{\"BU\", \"BU Name\", \"BU Type\"})",
                "in",
                "    #\"Removed Other Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "EdmMasterData dIncoterms",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Incoterms",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9da5a651-2c29-4b03-adf6-a90b241deba7",
            "sourceColumn": "Incoterms",
            "summarizeBy": "none"
          },
          {
            "name": "Incoterms Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b2eb130e-b4b6-4ad7-bfec-f06210e52cd0",
            "sourceColumn": "Incoterms Name",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "3eba5a15-fdee-46ef-a5ef-6353292cd4eb",
        "partitions": [
          {
            "name": "EdmMasterData dIncoterms-883c7fb0-901c-44c7-bb25-66c50f228436",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "",
                "/*",
                "    Source = Sql.Database(\"lyb-sql-stgdacore-002.5bff9fcb8330.database.windows.net\", \"Source\", [MultiSubnetFailover=true]),",
                "    EdmMasterData_vdIncotermsLoad = Source{[Schema=\"EdmMasterData\",Item=\"vdIncoterms\"]}[Data],",
                "*/",
                "\tSource = Snowflake.Databases(server,warehouse,[Role=role]),",
                "    DEV_SOURCE_Database = Source{[Name=db,Kind=\"Database\"]}[Data],",
                "    EDMMASTERDATA_Schema = DEV_SOURCE_Database{[Name=\"EDMMASTERDATA\",Kind=\"Schema\"]}[Data],",
                "    EdmMasterData_vdIncotermsLoad = EDMMASTERDATA_Schema{[Name=\"vdIncoterms\",Kind=\"View\"]}[Data],",
                "    #\"Removed Other Columns\" = Table.SelectColumns(EdmMasterData_vdIncotermsLoad,{\"Incoterms\", \"Incoterms Name\"})",
                "in",
                "    #\"Removed Other Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "EdmVendor dVendor",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Vendor",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7ad21cc4-ace5-463f-8d4d-8d4ad167d2a9",
            "sourceColumn": "Vendor",
            "summarizeBy": "none"
          },
          {
            "name": "Vendor Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5ad93118-1ce7-457a-a6e6-f618fe959572",
            "sourceColumn": "Vendor Name",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "7362b652-b0c4-4360-9e69-a7bb5140f951",
        "partitions": [
          {
            "name": "EdmVendor dVendor-07dadb61-ebbc-47d4-884e-6d9179fce2cf",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Value.NativeQuery(Snowflake.Databases(server,warehouse,[Role=role]){[Name=db]}[Data], \"SELECT DISTINCT \"\"Vendor\"\",\"\"Vendor Name\"\" FROM \"&db&\".EDMVENDOR.\"\"vdVendor\"\" \", null, [EnableFolding=true])",
                "in",
                "    Source",
                "",
                "",
                "/*",
                "let",
                "    Source = Sql.Database(\"lyb-sql-stgdacore-002.5bff9fcb8330.database.windows.net\", \"Source\", [Query=\"SELECT DISTINCT#(lf)[Vendor],[Vendor Name]#(lf)FROM EdmVendor.vdVendor\", MultiSubnetFailover=true])",
                "in",
                "    Source",
                "*/"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "EdmMasterData dPackageType",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Matl Pricing Grp 4",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "01358180-cb9b-4443-a0a7-41a4d0838c48",
            "sourceColumn": "Matl Pricing Grp 4",
            "summarizeBy": "none"
          },
          {
            "name": "Matl Pricing Grp 4 Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0fcbabc8-9d61-4def-a3ac-e9f1445a5b4d",
            "sourceColumn": "Matl Pricing Grp 4 Name",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "25935438-8b33-43f2-9f9b-9a88c236b26a",
        "partitions": [
          {
            "name": "EdmMasterData dPackageType-321d5a45-4fc5-4a50-ba91-a4b308840011",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "",
                "/*",
                "    Source = Sql.Database(\"lyb-sql-stgdacore-002.5bff9fcb8330.database.windows.net\", \"Source\", [MultiSubnetFailover=true]),",
                "    EdmMasterData_dPackageType = Source{[Schema=\"EdmMasterData\",Item=\"vdPackageType\"]}[Data],",
                "*/",
                "\tSource = Snowflake.Databases(server,warehouse,[Role=role]),",
                "    DEV_SOURCE_Database = Source{[Name=db,Kind=\"Database\"]}[Data],",
                "    EDMMASTERDATA_Schema = DEV_SOURCE_Database{[Name=\"EDMMASTERDATA\",Kind=\"Schema\"]}[Data],",
                "    EdmMasterData_dPackageType = EDMMASTERDATA_Schema{[Name=\"vdPackageType\",Kind=\"View\"]}[Data],",
                "    #\"Removed Other Columns\" = Table.SelectColumns(EdmMasterData_dPackageType,{\"Matl Pricing Grp 4\", \"Matl Pricing Grp 4 Name\"})",
                "in",
                "    #\"Removed Other Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "EdmMaterial dMaterial",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Material",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "70018d71-a0b9-47b7-b723-401eb7e7e927",
            "sourceColumn": "Material",
            "summarizeBy": "none"
          },
          {
            "name": "Material Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0eb121a7-78c3-46d5-8842-33eb9d54515c",
            "sourceColumn": "Material Name",
            "summarizeBy": "none"
          },
          {
            "name": "Prod Hierarchy",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8ba5f766-34bb-4d86-afc6-1724e53b9fe6",
            "sourceColumn": "Prod Hierarchy",
            "summarizeBy": "none"
          },
          {
            "name": "Prod Hierarchy Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "339fb2bb-6851-49cd-8bb7-c4c57fdb0d96",
            "sourceColumn": "Prod Hierarchy Name",
            "summarizeBy": "none"
          },
          {
            "name": "Prod Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1f175281-6dff-451d-91bb-7130750541df",
            "sourceColumn": "Prod Code",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "368e8cbb-143b-4016-b1be-6ce4bb5edce9",
        "partitions": [
          {
            "name": "EdmMaterial dMaterial-7cb5637f-62b7-4dfa-b5f6-71b5cdba18a4",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "   Source = Value.NativeQuery(Snowflake.Databases(server,warehouse,[Role=role]){[Name=db]}[Data], \"SELECT DISTINCT \"\"Material\"\",\"\"Material Name\"\",\"\"Prod Hierarchy\"\",\"\"Prod Hierarchy Name\"\",\"\"Prod Code\"\" FROM \"&db&\".EDMMATERIAL.\"\"vdMaterial\"\" \", null, [EnableFolding=true])",
                "in",
                "    Source",
                "",
                "/*",
                "let",
                "    Source = Sql.Database(\"lyb-sql-stgdacore-002.5bff9fcb8330.database.windows.net\", \"Source\", [Query=\"SELECT DISTINCT#(lf)[Material],[Material Name],[Prod Hierarchy],[Prod Hierarchy Name],[Prod Code]#(lf)FROM EdmMaterial.vdMaterial\", MultiSubnetFailover=true])",
                "in",
                "    Source",
                "*/"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "EdmCustomer dSoldToCustomer",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Sold To Customer",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d6cb98b9-1798-4193-87ed-470de8e6cbec",
            "sourceColumn": "Sold To Customer",
            "summarizeBy": "none"
          },
          {
            "name": "Sold To Customer Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "646713d6-0e5f-4cd5-a64e-7b5343e7c41a",
            "sourceColumn": "Sold To Customer Name",
            "summarizeBy": "none"
          },
          {
            "name": "Sold To City",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "26bff7e3-8062-4d15-a781-24624bd2d6e1",
            "sourceColumn": "Sold To City",
            "summarizeBy": "none"
          },
          {
            "name": "Sold To Postal Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "dd6c23b9-f53d-4658-acdf-16c3d7a441e1",
            "sourceColumn": "Sold To Postal Code",
            "summarizeBy": "none"
          },
          {
            "name": "Sold To Region",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2213725b-eed1-4386-9321-c037999f75c6",
            "sourceColumn": "Sold To Region",
            "summarizeBy": "none"
          },
          {
            "name": "Sold To Region Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5ecf59b5-113e-4cf1-a553-44558f4aa4d9",
            "sourceColumn": "Sold To Region Name",
            "summarizeBy": "none"
          },
          {
            "name": "Sold To Country",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "59c964dd-48aa-4018-a93c-f078572de022",
            "sourceColumn": "Sold To Country",
            "summarizeBy": "none"
          },
          {
            "name": "Sold To Country Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "83576017-da79-44bf-85c6-4cc15e2b9120",
            "sourceColumn": "Sold To Country Name",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "fb2eac8e-5fd6-482d-8747-3aa404db8fae",
        "partitions": [
          {
            "name": "EdmCustomer dSoldToCustomer-f35fe05d-252a-424b-953f-270858b938da",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "/*",
                "    Source = Sql.Database(\"lyb-sql-stgdacore-002.5bff9fcb8330.database.windows.net\", \"Source\", [Query=\"SELECT DISTINCT#(lf)[Customer],[Customer Name],[City],[Country],[Country Name],[Postal Code],[Region],[Region Name]#(lf)FROM EdmCustomer.vdCustomer\", MultiSubnetFailover=true]),",
                "*/",
                "    Source = Value.NativeQuery(Snowflake.Databases(server,warehouse,[Role=role]){[Name=db]}[Data], \"SELECT DISTINCT \"\"Customer\"\",\"\"Customer Name\"\",\"\"City\"\",\"\"Country\"\",\"\"Country Name\"\",\"\"Postal Code\"\",\"\"Region\"\",\"\"Region Name\"\" FROM \"&db&\".EDMCUSTOMER.\"\"vdCustomer\"\" \", null, [EnableFolding=true]),",
                "    #\"Renamed Columns\" = Table.RenameColumns(Source,{{\"City\", \"Sold To City\"}, {\"Country\", \"Sold To Country\"}, {\"Country Name\", \"Sold To Country Name\"}, {\"Customer\", \"Sold To Customer\"}, {\"Customer Name\", \"Sold To Customer Name\"}, {\"Postal Code\", \"Sold To Postal Code\"}, {\"Region\", \"Sold To Region\"}, {\"Region Name\", \"Sold To Region Name\"}})",
                "in",
                "    #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "EdmCustomer dShipToCustomer",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Ship To Customer",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9e253361-2e47-4896-b862-430ce329d016",
            "sourceColumn": "Ship To Customer",
            "summarizeBy": "none"
          },
          {
            "name": "Ship To Customer Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1157e802-fc17-4938-b364-5ced11c90b45",
            "sourceColumn": "Ship To Customer Name",
            "summarizeBy": "none"
          },
          {
            "name": "Ship To City",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6881d05c-00f5-4899-a01a-e898e7210aa3",
            "sourceColumn": "Ship To City",
            "summarizeBy": "none"
          },
          {
            "name": "Ship To Country",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a7d1b569-55ac-489e-a5b3-7434b0d24af8",
            "sourceColumn": "Ship To Country",
            "summarizeBy": "none"
          },
          {
            "name": "Ship To Country Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "87f10369-408d-4f7c-bde1-f0802179ccb5",
            "sourceColumn": "Ship To Country Name",
            "summarizeBy": "none"
          },
          {
            "name": "Ship To Postal Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d2e134e4-5f72-46f6-b9ea-16c5bf5e779c",
            "sourceColumn": "Ship To Postal Code",
            "summarizeBy": "none"
          },
          {
            "name": "Ship To Region",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f4f995c3-fefc-4fb4-b09c-2ed41b111f37",
            "sourceColumn": "Ship To Region",
            "summarizeBy": "none"
          },
          {
            "name": "Ship To Region Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f6871023-dd9d-436d-9ccd-ec1129c2f6de",
            "sourceColumn": "Ship To Region Name",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "b8d3c3eb-a8a9-4303-9b7b-9ba18a4e4810",
        "partitions": [
          {
            "name": "EdmCustomer dShipToCustomer-a899722f-0323-4207-97fb-7c475e3f2453",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "/*",
                "    Source = Sql.Database(\"lyb-sql-stgdacore-002.5bff9fcb8330.database.windows.net\", \"Source\", [Query=\"SELECT DISTINCT#(lf)[Customer],[Customer Name],[City],[Country],[Country Name],[Postal Code],[Region],[Region Name]#(lf)FROM EdmCustomer.vdCustomer\", MultiSubnetFailover=true]),",
                "*/",
                "    Source = Value.NativeQuery(Snowflake.Databases(server,warehouse,[Role=role]){[Name=db]}[Data], \"SELECT DISTINCT \"\"Customer\"\",\"\"Customer Name\"\",\"\"City\"\",\"\"Country\"\",\"\"Country Name\"\",\"\"Postal Code\"\",\"\"Region\"\",\"\"Region Name\"\" FROM \"&db&\".EDMCUSTOMER.\"\"vdCustomer\"\" \", null, [EnableFolding=true]),",
                "    #\"Renamed Columns\" = Table.RenameColumns(Source,{{\"City\", \"Ship To City\"}, {\"Country\", \"Ship To Country\"}, {\"Country Name\", \"Ship To Country Name\"}, {\"Customer\", \"Ship To Customer\"}, {\"Customer Name\", \"Ship To Customer Name\"}, {\"Postal Code\", \"Ship To Postal Code\"}, {\"Region\", \"Ship To Region\"}, {\"Region Name\", \"Ship To Region Name\"}})",
                "in",
                "    #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "EdmMasterData dCountry",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Country",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7ffbb751-e521-400b-8a01-610e6e9b73f1",
            "sourceColumn": "Country",
            "summarizeBy": "none"
          },
          {
            "name": "Final Destination Country",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ef52bba1-a972-4944-8fc5-39c4457bd563",
            "sourceColumn": "Final Destination Country",
            "summarizeBy": "none"
          },
          {
            "name": "Final Destination Region",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "LOOKUPVALUE('Final Destination County Zone'[SalesProfRegion],'Final Destination County Zone'[Country],'EdmMasterData dCountry'[Final Destination Country])",
            "isDataTypeInferred": true,
            "lineageTag": "baedb8ae-f5b3-4f64-9e63-fb1f1950a3c8",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "afe2c28b-fb63-42d7-9a24-d3b4a831f90e",
        "partitions": [
          {
            "name": "EdmMasterData dCountry-917ee1ae-955a-40c8-b13b-114f9a49c5b6",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "/*",
                "    Source = Sql.Database(\"lyb-sql-stgdacore-002.5bff9fcb8330.database.windows.net\", \"Source\", [Query=\"SELECT DISTINCT#(lf)[Country],[Country Name]#(lf)FROM EdmMasterData.vdCountry\", MultiSubnetFailover=true]),",
                "*/",
                "    Source = Value.NativeQuery(Snowflake.Databases(server,warehouse,[Role=role]){[Name=db]}[Data], \"SELECT DISTINCT \"\"Country\"\",\"\"Country Name\"\" FROM \"&db&\".EDMMASTERDATA.\"\"vdCountry\"\" \", null, [EnableFolding=true]),",
                "    #\"Renamed Columns\" = Table.RenameColumns(Source,{{\"Country Name\", \"Final Destination Country\"}})",
                "in",
                "    #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Last Refreshed Date Time",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "LastRefresh",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "07f5c3a8-fec8-48cd-8467-d39990f7fb76",
            "sourceColumn": "LastRefresh",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_f7b44c1a-a188-46de-b33c-be24e49e4e13"
                },
                "isDefault": true,
                "relationship": "4bc8090a-0b01-4a02-beca-019482234b70"
              }
            ]
          }
        ],
        "lineageTag": "4728d21e-d0d1-49ac-a7aa-34429ad27e4e",
        "partitions": [
          {
            "name": "Last Refreshed Date Time-2c5ea2d2-19ac-4891-a260-81372ef057fa",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "Source = #table(type table[LastRefresh=datetime], {{DateTime.LocalNow()}})",
                "in",
                "Source"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_f7b44c1a-a188-46de-b33c-be24e49e4e13",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "e45bacc1-ced8-4654-a766-8422f8cdc77a",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "f0af2068-98cf-4e1d-9bd2-8fa625bb7220",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "89c169b1-9c7e-4586-8853-9a92af256083",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "6f56817e-9637-458f-8f70-f538c0ba0369",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "2253677b-979a-45df-b1f2-38d56d4ccb30",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "d525064c-d41c-4f61-a6d3-ab377757f854",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "b5e95b9b-1dc8-4ea2-a6fb-80e2605a3e11",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "23d18129-8f59-435c-97a8-174573050c02",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "2cc50a66-c7bc-47ea-b2cd-f53777d82120",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "63142c04-d1e2-4527-9236-f4727508245c",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "f013fb57-77a6-4782-8d05-65ed23fef971",
                "ordinal": 3
              }
            ],
            "lineageTag": "9e0ba6e2-3839-4f28-8b12-e35519c00cfa"
          }
        ],
        "isHidden": true,
        "lineageTag": "d62c3041-d07d-40e3-a6fc-5b30bb51caf6",
        "partitions": [
          {
            "name": "LocalDateTable_f7b44c1a-a188-46de-b33c-be24e49e4e13-78797bbc-3354-4486-a3ae-3aba74d07923",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Last Refreshed Date Time'[LastRefresh])), 1, 1), Date(Year(MAX('Last Refreshed Date Time'[LastRefresh])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "Final Destination County Zone",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Country",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0fbe9b83-57fa-42e7-a9fb-1969603d98c6",
            "sourceColumn": "Country",
            "summarizeBy": "none"
          },
          {
            "name": "Region",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "41706cf2-84fb-4655-8bf9-f53010686e18",
            "sourceColumn": "Region",
            "summarizeBy": "none"
          },
          {
            "name": "Zone",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2505b287-8099-4daa-9ad7-cc0ee6cb99f7",
            "sourceColumn": "Zone",
            "summarizeBy": "none"
          },
          {
            "name": "SalesProfRegion",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a310a43d-76b7-440c-9043-57215397dc85",
            "sourceColumn": "SalesProfRegion",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "3521f236-2a10-4569-b1ac-8e4a3be3385e",
        "partitions": [
          {
            "name": "Final Destination County Zone-42ebe1ad-c8b6-4fa9-ae10-0779d2e34bf8",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = SharePoint.Tables(\"https://lyondellbasell.sharepoint.com/sites/LYBPowerBIUserGroup\", [ApiVersion = 15]),",
                "    #\"5a8b5248-0e62-4aac-ada6-49d3c44cfa09\" = Source{[Id=\"5a8b5248-0e62-4aac-ada6-49d3c44cfa09\"]}[Items],",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"5a8b5248-0e62-4aac-ada6-49d3c44cfa09\",{{\"ID\", \"ID.1\"}}),",
                "    #\"Removed Other Columns\" = Table.SelectColumns(#\"Renamed Columns\",{\"Title\", \"Region\", \"Zone\", \"SalesProfRegion\"}),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Removed Other Columns\",{{\"Title\", \"Country\"}})",
                "in",
                "    #\"Renamed Columns1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Top N Profitability Matrix",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "735294db8c6740ffbf832b548c1a568a"
          }
        ],
        "columns": [
          {
            "name": "Top N Profitability Matrix",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "c999abca-bda8-4da8-834e-7083ef9e7ff9",
            "relatedColumnDetails": {
              "groupByColumns": [
                {
                  "groupingColumn": "Top N Profitability Matrix Fields"
                }
              ]
            },
            "sortByColumn": "Top N Profitability Matrix Order",
            "sourceColumn": "[Value1]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Top N Profitability Matrix Fields",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "extendedProperties": [
              {
                "name": "ParameterMetadata",
                "type": "json",
                "value": {
                  "kind": 2,
                  "version": 3
                }
              }
            ],
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "8b8e5792-9c12-413a-a5e6-58d29a972550",
            "sortByColumn": "Top N Profitability Matrix Order",
            "sourceColumn": "[Value2]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Top N Profitability Matrix Order",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "f5ed7365-13de-4524-a686-2e94e2374e7e",
            "sourceColumn": "[Value3]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "0b7c22d7-1be5-4c10-8410-92e531c9e577",
        "partitions": [
          {
            "name": "Top N Profitability Matrix-57a825bd-8ccb-476d-bac5-e351d6084a9c",
            "mode": "import",
            "source": {
              "expression": [
                "{",
                "    (\"CM1\", NAMEOF('Measures Table'[Top N CM1]), 0),",
                "    (\"SAVPM\", NAMEOF('Measures Table'[Top N SAVPM]), 1)",
                "}"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Top N Profitability Matrix - PY",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "52296289bb8e474f896f2d0a2c8d56ac"
          }
        ],
        "columns": [
          {
            "name": "Top N Profitability Matrix - PY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "53ec3e7b-e5ff-40f2-82a6-093a4d01892b",
            "relatedColumnDetails": {
              "groupByColumns": [
                {
                  "groupingColumn": "Top N Profitability Matrix - PY Fields"
                }
              ]
            },
            "sortByColumn": "Top N Profitability Matrix - PY Order",
            "sourceColumn": "[Value1]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Top N Profitability Matrix - PY Fields",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "extendedProperties": [
              {
                "name": "ParameterMetadata",
                "type": "json",
                "value": {
                  "kind": 2,
                  "version": 3
                }
              }
            ],
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "0572258f-bded-4f26-baae-5c8c74c6a348",
            "sortByColumn": "Top N Profitability Matrix - PY Order",
            "sourceColumn": "[Value2]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Top N Profitability Matrix - PY Order",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "15e538c9-971e-493a-bb86-f0934a6b2b5b",
            "sourceColumn": "[Value3]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "e4166f9a-fd7b-44bd-8cc9-a063a944f192",
        "partitions": [
          {
            "name": "Top N Profitability Matrix - PY-a5a810dd-8399-45fd-8592-05d635da5886",
            "mode": "import",
            "source": {
              "expression": [
                "{",
                "    (\"PY CM1\", NAMEOF('Measures Table'[Top N CM1 (PY)]), 0),",
                "    (\"PY SAVPM\", NAMEOF('Measures Table'[Top N SAVPM (PY)]), 1)",
                "}"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Top N CM1/SAVPM Margin Per Unit",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "94a108bbf96c4c409bf25b7c1ba5aaec"
          }
        ],
        "columns": [
          {
            "name": "Top N CM1/SAVPM Margin Per Unit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "4134e617-74a0-4aa7-8a55-65aad0f78624",
            "relatedColumnDetails": {
              "groupByColumns": [
                {
                  "groupingColumn": "Top N CM1/SAVPM Margin Per Unit Fields"
                }
              ]
            },
            "sortByColumn": "Top N CM1/SAVPM Margin Per Unit Order",
            "sourceColumn": "[Value1]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Top N CM1/SAVPM Margin Per Unit Fields",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "extendedProperties": [
              {
                "name": "ParameterMetadata",
                "type": "json",
                "value": {
                  "kind": 2,
                  "version": 3
                }
              }
            ],
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "f31b5721-80e7-4cb0-a31b-f30dccc626a1",
            "sortByColumn": "Top N CM1/SAVPM Margin Per Unit Order",
            "sourceColumn": "[Value2]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Top N CM1/SAVPM Margin Per Unit Order",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "9e3de85e-7287-4e0d-8de5-affc0b37a986",
            "sourceColumn": "[Value3]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "63e6c383-19f4-40fa-aaf4-542c451c8487",
        "partitions": [
          {
            "name": "Top N CM1/SAVPM Margin Per Unit-3b07985a-3bff-411e-9b2f-070d46f2c62b",
            "mode": "import",
            "source": {
              "expression": [
                "{",
                "    (\"CM1 Per Unit Margin\", NAMEOF('Measures Table'[Top N CM1/Unit]), 0),",
                "    (\"SAVPM Per Unit Margin\", NAMEOF('Measures Table'[Top N SAVPM/Unit]), 1)",
                "}"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Top N PY CM1/SAVPM Margin Per Unit",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "323e404dbec244089391bc1b91991ed6"
          }
        ],
        "columns": [
          {
            "name": "Top N PY CM1/SAVPM Margin Per Unit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "22a23404-66f2-4036-ad6a-fe8123d23faa",
            "relatedColumnDetails": {
              "groupByColumns": [
                {
                  "groupingColumn": "Top N PY CM1/SAVPM Margin Per Unit Fields"
                }
              ]
            },
            "sortByColumn": "Top N PY CM1/SAVPM Margin Per Unit Order",
            "sourceColumn": "[Value1]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Top N PY CM1/SAVPM Margin Per Unit Fields",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "extendedProperties": [
              {
                "name": "ParameterMetadata",
                "type": "json",
                "value": {
                  "kind": 2,
                  "version": 3
                }
              }
            ],
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "8e4a5c28-0e16-4151-9432-97482be4b308",
            "sortByColumn": "Top N PY CM1/SAVPM Margin Per Unit Order",
            "sourceColumn": "[Value2]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Top N PY CM1/SAVPM Margin Per Unit Order",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "de9a0512-7ec9-4155-8fb1-5ffbfc09eb23",
            "sourceColumn": "[Value3]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "9390abf7-60dd-43fa-8368-168bb8c3d484",
        "partitions": [
          {
            "name": "Top N PY CM1/SAVPM Margin Per Unit-8e7dab3d-1b34-4696-b65a-bda4541d0e2e",
            "mode": "import",
            "source": {
              "expression": [
                "{",
                "    (\"PY - CM1 Per Unit Margin\", NAMEOF('Measures Table'[Top N CM1/Unit (PY)]), 0),",
                "    (\"PY - SAVPM Per Unit Margin\", NAMEOF('Measures Table'[Top N SAVPM/Unit (PY)]), 1)",
                "}"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Product or Material",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "2be6a660dd794d6db42bce665c15d8a1"
          }
        ],
        "columns": [
          {
            "name": "Product or Material",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "5a35551a-0c1f-4e55-a786-543e4bb1848f",
            "relatedColumnDetails": {
              "groupByColumns": [
                {
                  "groupingColumn": "Product or Material Fields"
                }
              ]
            },
            "sortByColumn": "Product or Material Order",
            "sourceColumn": "[Value1]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Product or Material Fields",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "extendedProperties": [
              {
                "name": "ParameterMetadata",
                "type": "json",
                "value": {
                  "kind": 2,
                  "version": 3
                }
              }
            ],
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "e971dae7-85f5-47c9-90af-fb8b84d9fd3d",
            "sortByColumn": "Product or Material Order",
            "sourceColumn": "[Value2]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Product or Material Order",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "1d83bee6-653f-4a8c-8f43-08a7013a7b1b",
            "sourceColumn": "[Value3]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "b7fa31e3-5e48-4c66-88fb-dd5f2429e669",
        "partitions": [
          {
            "name": "Product or Material-30fdbc4b-ca97-4b33-9e05-eba6efe6a933",
            "mode": "import",
            "source": {
              "expression": [
                "{",
                "    (\"Product\", NAMEOF('EdmMaterial dMaterial'[Prod Hierarchy Name]), 0),",
                "    (\"Material\", NAMEOF('EdmMaterial dMaterial'[Material Name]), 1)",
                "}"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Show/Hide",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "aefe64f25b884e45a0536d84955079a3"
          }
        ],
        "columns": [
          {
            "name": "Show/Hide",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "6bf015e7-8f1f-49cb-ba8f-c9fb69b03940",
            "sourceColumn": "[Show/Hide]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "2f6d08f4-10b2-47d0-a38a-31e04b5c45b1",
        "partitions": [
          {
            "name": "Show/Hide",
            "mode": "import",
            "source": {
              "expression": [
                "DATATABLE(\"Show/Hide\",STRING,",
                "{",
                "    {\"Show\"},",
                "    {\"Hide\"}",
                "}",
                ")",
                "",
                "",
                ""
              ],
              "type": "calculated"
            }
          }
        ]
      }
    ]
  }
}